/**
 * Building definitions for Epoch Nations
 * Each building has: id, name, category, epoch_required, description,
 * cost (resources + treasury), workforce, benefits, populationCap (max 1 per X pop)
 */

export const BUILDINGS = [
  // ── CIVILIAN ──────────────────────────────────────────────────────────────
  {
    id: "house",
    name: "Houses",
    emoji: "🏠",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Increases population cap and morale.",
    cost: { res_wood: 50, res_stone: 30, currency: 50 },
    workforce: 0,
    benefits: { housing_capacity: 20, stability: 2 },
    populationCap: null,
  },
  {
    id: "farm",
    name: "Farm",
    emoji: "🌾",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Produces food passively each tick (+8 food/tick).",
    cost: { res_wood: 40, res_stone: 20, currency: 60 },
    workforce: 2,
    benefits: { farmBonus: 8 },
    populationCap: null,
  },
  {
    id: "school",
    name: "School",
    emoji: "🏫",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Generates +10 TP per tick. Requires 1 teacher.",
    cost: { res_wood: 80, res_stone: 60, currency: 150 },
    workforce: 1,
    benefits: { tpBonus: 10, stability: 2 },
    populationCap: 100, // 1 per 100 pop
  },
  {
    id: "hospital",
    name: "Hospital",
    emoji: "🏥",
    category: "civilian",
    epoch_required: "Middle Ages",
    description: "Increases stability and population survival rate.",
    cost: { res_stone: 150, res_gold: 100, currency: 400 },
    workforce: 2,
    benefits: { stability: 8, public_trust: 0.1 },
    populationCap: 500,
  },
  {
    id: "market",
    name: "Market",
    emoji: "🏪",
    category: "civilian",
    epoch_required: "Copper Age",
    description: "Boosts GDP and trade income.",
    cost: { res_wood: 100, res_stone: 80, currency: 200 },
    workforce: 2,
    benefits: { gdp: 150, currency: 50 },
    populationCap: null,
  },
  {
    id: "university",
    name: "University",
    emoji: "🎓",
    category: "civilian",
    epoch_required: "Renaissance",
    description: "Generates +35 TP per tick. Required for advanced epochs.",
    cost: { res_wood: 200, res_stone: 300, res_gold: 150, currency: 1000 },
    workforce: 3,
    benefits: { tpBonus: 35, stability: 5, gdp: 200 },
    populationCap: 300,
  },

  // ── MILITARY ──────────────────────────────────────────────────────────────
  {
    id: "barracks",
    name: "Barracks",
    emoji: "⚔️",
    category: "military",
    epoch_required: "Stone Age",
    description: "Increases unit power and training capacity.",
    cost: { res_wood: 60, res_stone: 80, currency: 120 },
    workforce: 2,
    benefits: { unit_power: 10, defense_level: 5 },
    populationCap: null,
  },
  {
    id: "siege_workshop",
    name: "Siege Workshop",
    emoji: "🏹",
    category: "military",
    epoch_required: "Middle Ages",
    description: "Unlocks siege capabilities and boosts attack.",
    cost: { res_wood: 150, res_iron: 100, currency: 300 },
    workforce: 2,
    benefits: { unit_power: 20, defense_level: 10 },
    populationCap: null,
  },
  {
    id: "defense_lab",
    name: "Defense Lab",
    emoji: "🔬",
    category: "military",
    epoch_required: "Industrial Age",
    description: "Significantly boosts defense capabilities.",
    cost: { res_stone: 200, res_iron: 150, res_gold: 200, currency: 800 },
    workforce: 3,
    benefits: { defense_level: 30, unit_power: 15 },
    populationCap: null,
  },
  {
    id: "air_base",
    name: "Air Base",
    emoji: "✈️",
    category: "military",
    epoch_required: "Modern Age",
    description: "Advanced aerial capabilities.",
    cost: { res_iron: 300, res_gold: 400, currency: 2000 },
    workforce: 4,
    benefits: { unit_power: 50, defense_level: 25 },
    populationCap: null,
  },
  {
    id: "naval_yard",
    name: "Naval Yard",
    emoji: "⚓",
    category: "military",
    epoch_required: "Imperial Age",
    description: "Naval warfare and trade capabilities.",
    cost: { res_wood: 300, res_iron: 200, currency: 1000 },
    workforce: 3,
    benefits: { unit_power: 30, gdp: 200, defense_level: 20 },
    populationCap: null,
  },

  // ── GOVERNMENT ────────────────────────────────────────────────────────────
  {
    id: "capital",
    name: "Government Capital",
    emoji: "🏛️",
    category: "government",
    epoch_required: "Bronze Age",
    description: "Stability boost, tax efficiency, and governance.",
    cost: { res_stone: 200, res_wood: 100, res_gold: 50, currency: 500 },
    workforce: 2,
    benefits: { stability: 15, gdp: 300, public_trust: 0.15 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "intelligence_agency",
    name: "Intelligence Agency",
    emoji: "🕵️",
    category: "government",
    epoch_required: "Industrial Age",
    description: "Increases migration rate, espionage bonuses, public trust.",
    cost: { res_gold: 300, currency: 2000 },
    workforce: 3,
    benefits: { stability: 10, public_trust: 0.2, migrationBonus: 2 },
    populationCap: 1000,
    uniqueMax: 1,
  },
  {
    id: "military_foundry",
    name: "Military Foundry",
    emoji: "⚙️",
    category: "government",
    epoch_required: "Iron Age",
    description: "Produces military equipment, requires Iron.",
    cost: { res_iron: 150, res_stone: 200, currency: 600 },
    workforce: 3,
    benefits: { unit_power: 25, manufacturing: 15, defense_level: 15 },
    populationCap: null,
  },
];

export const BUILDING_MAP = Object.fromEntries(BUILDINGS.map(b => [b.id, b]));

/**
 * Epoch advancement requirements
 * Each epoch specifies what's needed to advance TO the NEXT epoch
 */
export const EPOCH_REQUIREMENTS = {
  "Stone Age": {
    tp: 50,
    population: 30,
    buildings: { school: 1 },
    resources: { res_wood: 100, res_stone: 80 },
  },
  "Copper Age": {
    tp: 120,
    population: 60,
    buildings: { school: 1, house: 2 },
    resources: { res_wood: 200, res_stone: 150, res_gold: 30 },
  },
  "Bronze Age": {
    tp: 200,
    population: 100,
    buildings: { school: 1, capital: 1 },
    resources: { res_wood: 300, res_stone: 200, res_gold: 80 },
  },
  "Iron Age": {
    tp: 300,
    population: 150,
    buildings: { school: 1, barracks: 1, military_foundry: 1 },
    resources: { res_iron: 100, res_stone: 200, res_gold: 100 },
  },
  "Dark Ages": {
    tp: 400,
    population: 200,
    buildings: { school: 2, barracks: 1 },
    resources: { res_wood: 400, res_stone: 300, res_iron: 150, res_gold: 150 },
  },
  "Middle Ages": {
    tp: 550,
    population: 300,
    buildings: { school: 2, hospital: 1, barracks: 1 },
    resources: { res_stone: 400, res_iron: 200, res_gold: 200 },
  },
  "Renaissance": {
    tp: 700,
    population: 400,
    buildings: { school: 2, market: 2, capital: 1 },
    resources: { res_gold: 300, res_stone: 400 },
  },
  "Imperial Age": {
    tp: 900,
    population: 500,
    buildings: { university: 1, capital: 1, naval_yard: 1 },
    resources: { res_gold: 500, res_iron: 300, res_wood: 500 },
  },
  "Enlightenment Age": {
    tp: 1200,
    population: 600,
    buildings: { university: 1, capital: 1 },
    resources: { res_gold: 600, res_iron: 400 },
  },
  "Industrial Age": {
    tp: 1600,
    population: 800,
    buildings: { university: 2, capital: 1, military_foundry: 1, defense_lab: 1 },
    resources: { res_gold: 800, res_iron: 600 },
  },
  "Modern Age": {
    tp: 2200,
    population: 1000,
    buildings: { university: 2, intelligence_agency: 1, air_base: 1 },
    resources: { res_gold: 1200, res_oil: 500 },
  },
  "Atomic Age": {
    tp: 3000,
    population: 1200,
    buildings: { university: 3, defense_lab: 1, air_base: 1 },
    resources: { res_gold: 2000, res_oil: 1000 },
  },
  "Digital Age": {
    tp: 4000,
    population: 1500,
    buildings: { university: 3, intelligence_agency: 1 },
    resources: { res_gold: 3000 },
  },
  "Genetic Age": {
    tp: 5500,
    population: 2000,
    buildings: { university: 3, capital: 1 },
    resources: { res_gold: 5000 },
  },
  "Synthetic Age": {
    tp: 7500,
    population: 2500,
    buildings: { university: 4, defense_lab: 1 },
    resources: { res_gold: 8000 },
  },
  // Nano Age is final — no requirements
};