/**
 * Building definitions for Epoch Nations
 * Each building has: id, name, category, epoch_required, description,
 * cost (resources + treasury), workforce, benefits, populationCap
 */

export const BUILDINGS = [
  // ── CIVILIAN ──────────────────────────────────────────────────────────────
  {
    id: "house",
    name: "Houses",
    emoji: "🏠",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Increases population cap and morale.",
    cost: { res_wood: 50, res_stone: 30, currency: 50 },
    workforce: 0,
    benefits: { housing_capacity: 20, stability: 2 },
    populationCap: null,
  },
  {
    id: "farm",
    name: "Farm",
    emoji: "🌾",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Produces food passively each tick (+8 food/tick).",
    cost: { res_wood: 40, res_stone: 20, currency: 60 },
    workforce: 2,
    benefits: { farmBonus: 8 },
    populationCap: null,
  },
  {
    id: "school",
    name: "School",
    emoji: "🏫",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Generates +10 TP per tick. Requires 1 teacher.",
    cost: { res_wood: 80, res_stone: 60, currency: 150 },
    workforce: 1,
    benefits: { tpBonus: 10, stability: 2 },
    populationCap: 50,
  },
  {
    id: "well",
    name: "Water Well",
    emoji: "⛲",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Improves public health and stability.",
    cost: { res_stone: 40, res_wood: 20, currency: 40 },
    workforce: 0,
    benefits: { stability: 3, public_trust: 0.05 },
    populationCap: null,
  },
  {
    id: "granary",
    name: "Granary",
    emoji: "🌽",
    category: "civilian",
    epoch_required: "Bronze Age",
    description: "Stores extra food reserves. Increases food cap and stability.",
    cost: { res_wood: 70, res_stone: 50, currency: 100 },
    workforce: 1,
    benefits: { farmBonus: 5, stability: 4 },
    populationCap: null,
  },
  {
    id: "market",
    name: "Market",
    emoji: "🏪",
    category: "civilian",
    epoch_required: "Bronze Age",
    description: "Boosts GDP and trade income.",
    cost: { res_wood: 100, res_stone: 80, currency: 200 },
    workforce: 2,
    benefits: { gdp: 150, currency: 50 },
    populationCap: null,
  },
  {
    id: "tavern",
    name: "Tavern",
    emoji: "🍺",
    category: "civilian",
    epoch_required: "Bronze Age",
    description: "Boosts morale and public trust. Small GDP boost from alcohol taxes.",
    cost: { res_wood: 80, res_stone: 40, currency: 120 },
    workforce: 1,
    benefits: { stability: 5, public_trust: 0.07, gdp: 60 },
    populationCap: null,
  },
  {
    id: "hospital",
    name: "Hospital",
    emoji: "🏥",
    category: "civilian",
    epoch_required: "Medieval Age",
    description: "Increases stability and population survival rate.",
    cost: { res_stone: 150, res_gold: 100, currency: 400 },
    workforce: 2,
    benefits: { stability: 8, public_trust: 0.1 },
    populationCap: 500,
  },
  {
    id: "college",
    name: "College",
    emoji: "🏫",
    category: "civilian",
    epoch_required: "Bronze Age",
    description: "Trains middle-class workers: engineers, managers, technicians. Generates +8 TP per tick. Stores up to 3,000 TP.",
    cost: { res_wood: 120, res_stone: 100, res_gold: 60, currency: 400 },
    workforce: 2,
    benefits: { tpBonus: 8, stability: 3, gdp: 100 },
    populationCap: 150,
  },
  {
    id: "university",
    name: "University",
    emoji: "🎓",
    category: "civilian",
    epoch_required: "Renaissance Age",
    description: "Trains scientists, economists, and AI researchers. Generates +35 TP per tick. Stores up to 6,000 TP.",
    cost: { res_wood: 200, res_stone: 300, res_gold: 150, currency: 1000 },
    workforce: 3,
    benefits: { tpBonus: 35, stability: 5, gdp: 200 },
    populationCap: 300,
  },
  {
    id: "bank",
    name: "National Bank",
    emoji: "🏦",
    category: "civilian",
    epoch_required: "Renaissance Age",
    description: "Earns passive treasury income each tick. Stabilizes economy.",
    cost: { res_gold: 200, res_stone: 150, currency: 800 },
    workforce: 2,
    benefits: { gdp: 300, currency: 150, public_trust: 0.08 },
    populationCap: null,
    uniqueMax: 2,
  },
  {
    id: "radio_station",
    name: "Radio Station",
    emoji: "📻",
    category: "civilian",
    epoch_required: "Industrial Age",
    description: "Boosts public trust and national morale through broadcasting.",
    cost: { res_iron: 100, res_gold: 150, currency: 500 },
    workforce: 1,
    benefits: { stability: 6, public_trust: 0.12 },
    populationCap: null,
    uniqueMax: 2,
  },
  {
    id: "shopping_mall",
    name: "Shopping Mall",
    emoji: "🏬",
    category: "civilian",
    epoch_required: "Modern Age",
    description: "Major GDP boost. Attracts migrants and raises living standards.",
    cost: { res_iron: 200, res_gold: 300, currency: 2000 },
    workforce: 3,
    benefits: { gdp: 500, migrationBonus: 2, public_trust: 0.1 },
    populationCap: null,
  },

  // ── MILITARY ──────────────────────────────────────────────────────────────
  {
    id: "barracks",
    name: "Barracks",
    emoji: "⚔️",
    category: "military",
    epoch_required: "Stone Age",
    description: "Increases unit power and training capacity.",
    cost: { res_wood: 60, res_stone: 80, currency: 120 },
    workforce: 2,
    benefits: { unit_power: 10, defense_level: 5 },
    populationCap: null,
  },
  {
    id: "watchtower",
    name: "Watch Tower",
    emoji: "🗼",
    category: "military",
    epoch_required: "Stone Age",
    description: "Early warning system. Boosts defense level.",
    cost: { res_stone: 60, res_wood: 40, currency: 80 },
    workforce: 1,
    benefits: { defense_level: 8 },
    populationCap: null,
  },
  {
    id: "armory",
    name: "Armory",
    emoji: "🛡️",
    category: "military",
    epoch_required: "Bronze Age",
    description: "Stores weapons and upgrades troops. Boosts unit power.",
    cost: { res_iron: 60, res_stone: 80, currency: 200 },
    workforce: 1,
    benefits: { unit_power: 12, defense_level: 8 },
    populationCap: null,
  },
  {
    id: "siege_workshop",
    name: "Siege Workshop",
    emoji: "🏹",
    category: "military",
    epoch_required: "Medieval Age",
    description: "Unlocks siege capabilities and boosts attack.",
    cost: { res_wood: 150, res_iron: 100, currency: 300 },
    workforce: 2,
    benefits: { unit_power: 20, defense_level: 10 },
    populationCap: null,
  },
  {
    id: "fort",
    name: "Fortification",
    emoji: "🏰",
    category: "military",
    epoch_required: "Classical Age",
    description: "Heavy defensive walls. Significantly boosts defense.",
    cost: { res_stone: 300, res_iron: 100, currency: 600 },
    workforce: 1,
    benefits: { defense_level: 25, stability: 4 },
    populationCap: null,
  },
  {
    id: "naval_yard",
    name: "Naval Yard",
    emoji: "⚓️",
    category: "military",
    epoch_required: "Medieval Age",
    description: "Naval warfare and trade capabilities.",
    cost: { res_wood: 300, res_iron: 200, currency: 1000 },
    workforce: 3,
    benefits: { unit_power: 30, gdp: 200, defense_level: 20 },
    populationCap: null,
  },
  {
    id: "defense_lab",
    name: "Defense Lab",
    emoji: "🔬",
    category: "military",
    epoch_required: "Industrial Age",
    description: "Significantly boosts defense capabilities.",
    cost: { res_stone: 200, res_iron: 150, res_gold: 200, currency: 800 },
    workforce: 3,
    benefits: { defense_level: 30, unit_power: 15 },
    populationCap: null,
  },
  {
    id: "air_base",
    name: "Air Base",
    emoji: "✈️",
    category: "military",
    epoch_required: "Modern Age",
    description: "Advanced aerial capabilities.",
    cost: { res_iron: 300, res_gold: 400, currency: 2000 },
    workforce: 4,
    benefits: { unit_power: 50, defense_level: 25 },
    populationCap: null,
  },
  {
    id: "missile_silo",
    name: "Missile Silo",
    emoji: "🚀",
    category: "military",
    epoch_required: "Information Age",
    description: "Nuclear deterrence. Massive unit power boost.",
    cost: { res_iron: 500, res_gold: 800, currency: 5000 },
    workforce: 4,
    benefits: { unit_power: 100, defense_level: 50 },
    populationCap: null,
    uniqueMax: 2,
  },
  {
    id: "cyber_command",
    name: "Cyber Command",
    emoji: "💻",
    category: "military",
    epoch_required: "Digital Age",
    description: "Cyber warfare capabilities. Intelligence and defense boost.",
    cost: { res_gold: 600, currency: 4000 },
    workforce: 3,
    benefits: { unit_power: 60, defense_level: 40, tpBonus: 20 },
    populationCap: null,
    uniqueMax: 1,
  },

  // ── RECREATIONAL ──────────────────────────────────────────────────────────
  {
    id: "park",
    name: "Public Park",
    emoji: "🌳",
    category: "recreational",
    epoch_required: "Stone Age",
    description: "Boosts citizen happiness, stability, and migration.",
    cost: { res_wood: 30, currency: 60 },
    workforce: 0,
    benefits: { stability: 4, migrationBonus: 1 },
    populationCap: null,
  },
  {
    id: "amphitheater",
    name: "Amphitheater",
    emoji: "🏟️",
    category: "recreational",
    epoch_required: "Bronze Age",
    description: "Public entertainment venue. Boosts trust and morale.",
    cost: { res_stone: 100, res_wood: 60, currency: 180 },
    workforce: 1,
    benefits: { stability: 6, public_trust: 0.08, gdp: 50 },
    populationCap: null,
  },
  {
    id: "library",
    name: "Library",
    emoji: "📚",
    category: "recreational",
    epoch_required: "Bronze Age",
    description: "Boosts research and public education. Adds TP each tick.",
    cost: { res_wood: 80, res_stone: 60, currency: 150 },
    workforce: 1,
    benefits: { tpBonus: 8, public_trust: 0.06, stability: 3 },
    populationCap: null,
  },
  {
    id: "stadium",
    name: "Sports Stadium",
    emoji: "🏆",
    category: "recreational",
    epoch_required: "Industrial Age",
    description: "Major morale booster. Generates significant GDP from events.",
    cost: { res_iron: 150, res_stone: 200, currency: 800 },
    workforce: 2,
    benefits: { stability: 10, public_trust: 0.12, gdp: 200, migrationBonus: 2 },
    populationCap: null,
    uniqueMax: 2,
  },
  {
    id: "theater",
    name: "Theater & Arts Center",
    emoji: "🎭",
    category: "recreational",
    epoch_required: "Renaissance",
    description: "Cultural hub. Boosts public trust and migration attractiveness.",
    cost: { res_stone: 120, res_gold: 80, currency: 400 },
    workforce: 1,
    benefits: { public_trust: 0.10, stability: 5, migrationBonus: 1 },
    populationCap: null,
  },
  {
    id: "amusement_park",
    name: "Amusement Park",
    emoji: "🎡",
    category: "recreational",
    epoch_required: "Modern Age",
    description: "Tourist destination. GDP boost and high public happiness.",
    cost: { res_iron: 200, res_gold: 300, currency: 2000 },
    workforce: 2,
    benefits: { gdp: 300, stability: 8, public_trust: 0.15, migrationBonus: 3 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "casino",
    name: "Casino & Resort",
    emoji: "🎰",
    category: "recreational",
    epoch_required: "Modern Age",
    description: "High revenue generator but slightly reduces stability.",
    cost: { res_gold: 400, currency: 3000 },
    workforce: 3,
    benefits: { gdp: 500, currency: 200 },
    populationCap: null,
    uniqueMax: 2,
  },
  {
    id: "national_museum",
    name: "National Museum",
    emoji: "🏛️",
    category: "recreational",
    epoch_required: "Industrial Age",
    description: "Showcases national history. Boosts trust, tourism, and tech.",
    cost: { res_stone: 200, res_gold: 200, currency: 1500 },
    workforce: 1,
    benefits: { public_trust: 0.15, tpBonus: 12, stability: 6, migrationBonus: 2 },
    populationCap: null,
    uniqueMax: 1,
  },

  // ── GOVERNMENT ────────────────────────────────────────────────────────────
  {
    id: "capital",
    name: "Government Capital",
    emoji: "🏛️",
    category: "government",
    epoch_required: "Bronze Age",
    description: "Stability boost, tax efficiency, and governance.",
    cost: { res_stone: 200, res_wood: 100, res_gold: 50, currency: 500 },
    workforce: 2,
    benefits: { stability: 15, gdp: 300, public_trust: 0.15 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "courthouse",
    name: "Courthouse",
    emoji: "⚖️",
    category: "government",
    epoch_required: "Iron Age",
    description: "Enforces law and reduces crime. Boosts stability and trust.",
    cost: { res_stone: 120, res_wood: 80, currency: 300 },
    workforce: 1,
    benefits: { stability: 8, public_trust: 0.1 },
    populationCap: null,
  },
  {
    id: "military_foundry",
    name: "Military Foundry",
    emoji: "🏭",
    category: "government",
    epoch_required: "Iron Age",
    description: "Produces military equipment, requires Iron.",
    cost: { res_iron: 150, res_stone: 200, currency: 600 },
    workforce: 3,
    benefits: { unit_power: 25, manufacturing: 15, defense_level: 15 },
    populationCap: null,
  },
  {
    id: "post_office",
    name: "Post Office",
    emoji: "📮",
    category: "government",
    epoch_required: "Middle Ages",
    description: "Improves communication and government efficiency. Boosts GDP.",
    cost: { res_wood: 60, res_stone: 40, currency: 200 },
    workforce: 1,
    benefits: { gdp: 80, public_trust: 0.06 },
    populationCap: null,
  },
  {
    id: "embassy",
    name: "Embassy",
    emoji: "🤝",
    category: "government",
    epoch_required: "Renaissance Age",
    description: "Diplomatic hub. Increases migration and alliance opportunities.",
    cost: { res_gold: 150, res_stone: 100, currency: 600 },
    workforce: 1,
    benefits: { migrationBonus: 3, public_trust: 0.1, gdp: 100 },
    populationCap: null,
    uniqueMax: 2,
  },
  {
    id: "intelligence_agency",
    name: "Intelligence Agency",
    emoji: "🕵️",
    category: "government",
    epoch_required: "Industrial Age",
    description: "Increases migration rate, espionage bonuses, public trust.",
    cost: { res_gold: 300, currency: 2000 },
    workforce: 3,
    benefits: { stability: 10, public_trust: 0.2, migrationBonus: 2 },
    populationCap: 1000,
    uniqueMax: 1,
  },
  {
    id: "treasury_building",
    name: "Treasury Building",
    emoji: "💰",
    category: "government",
    epoch_required: "Renaissance Age",
    description: "Increases tax collection efficiency and treasury income.",
    cost: { res_stone: 200, res_gold: 150, currency: 800 },
    workforce: 2,
    benefits: { gdp: 250, currency: 100 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "census_bureau",
    name: "Census Bureau",
    emoji: "📊",
    category: "government",
    epoch_required: "Industrial Age",
    description: "Tracks population data. Boosts resource efficiency and planning.",
    cost: { res_gold: 200, currency: 1000 },
    workforce: 1,
    benefits: { stability: 6, tpBonus: 10, public_trust: 0.08 },
    populationCap: null,
    uniqueMax: 1,
  },

  // ── INDUSTRIAL/PRODUCTION ──────────────────────────────────────────────────
  {
    id: "lumber_mill",
    name: "Lumber Mill",
    emoji: "🪚",
    category: "civilian",
    epoch_required: "Bronze Age",
    description: "Produces wood passively (+15 wood/tick). Requires 2 lumberjacks.",
    cost: { res_wood: 100, res_stone: 60, currency: 150 },
    workforce: 2,
    benefits: { woodBonus: 15, manufacturing: 10 },
    populationCap: null,
  },
  {
    id: "stone_quarry",
    name: "Stone Quarry",
    emoji: "⛏️",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Produces stone passively (+20 stone/tick). Requires 1 quarry worker.",
    cost: { res_wood: 50, res_stone: 40, currency: 80 },
    workforce: 1,
    benefits: { stoneBonus: 20, manufacturing: 5 },
    populationCap: null,
  },
  {
    id: "iron_forge",
    name: "Iron Forge",
    emoji: "🔨",
    category: "civilian",
    epoch_required: "Iron Age",
    description: "Produces iron and weapons. Requires iron ore.",
    cost: { res_iron: 100, res_stone: 100, currency: 300 },
    workforce: 2,
    benefits: { ironBonus: 12, unit_power: 10, manufacturing: 20 },
    populationCap: null,
  },
  {
    id: "gold_mine",
    name: "Gold Mine",
    emoji: "✨",
    category: "civilian",
    epoch_required: "Copper Age",
    description: "Produces gold ore and bullion (+8 gold/tick).",
    cost: { res_stone: 150, res_iron: 80, currency: 400 },
    workforce: 2,
    benefits: { goldBonus: 8, gdp: 100 },
    populationCap: null,
  },
  {
    id: "fishery",
    name: "Fishery",
    emoji: "🎣",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Produces food from aquatic resources (+10 food/tick).",
    cost: { res_wood: 60, currency: 100 },
    workforce: 1,
    benefits: { foodBonus: 10 },
    populationCap: null,
  },
  {
    id: "textile_factory",
    name: "Textile Factory",
    emoji: "🧵",
    category: "civilian",
    epoch_required: "Industrial Age",
    description: "Produces cloth and goods. Boosts GDP and exports.",
    cost: { res_wood: 200, res_iron: 100, currency: 600 },
    workforce: 3,
    benefits: { gdp: 200, manufacturing: 25 },
    populationCap: null,
  },
  {
    id: "brewery",
    name: "Brewery",
    emoji: "🍻",
    category: "civilian",
    epoch_required: "Bronze Age",
    description: "Produces beverages. Boosts GDP and morale.",
    cost: { res_stone: 100, res_wood: 80, currency: 200 },
    workforce: 1,
    benefits: { gdp: 80, stability: 3 },
    populationCap: null,
  },
  {
    id: "oil_refinery",
    name: "Oil Refinery",
    emoji: "🏭",
    category: "civilian",
    epoch_required: "Industrial Age",
    description: "Refines crude oil into fuel and lubricants.",
    cost: { res_iron: 200, res_gold: 150, currency: 1200 },
    workforce: 3,
    benefits: { gdp: 250, manufacturing: 30 },
    populationCap: null,
  },
  {
    id: "uranium_enrichment",
    name: "Uranium Enrichment Plant",
    emoji: "☢️",
    category: "civilian",
    epoch_required: "Information Age",
    description: "Processes uranium for fuel and weapons. Massive power output.",
    cost: { res_gold: 1000, currency: 4000 },
    workforce: 4,
    benefits: { gdp: 500, unit_power: 50, manufacturing: 40 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "semiconductor_fab",
    name: "Semiconductor Fab",
    emoji: "🔌",
    category: "civilian",
    epoch_required: "Digital Age",
    description: "Produces computing chips. Massive GDP and tech boost.",
    cost: { res_gold: 1500, currency: 5000 },
    workforce: 4,
    benefits: { gdp: 600, tpBonus: 50, manufacturing: 50 },
    populationCap: null,
    uniqueMax: 1,
  },

  // ── MORE MILITARY ──────────────────────────────────────────────────────────
  {
    id: "gun_factory",
    name: "Gun Factory",
    emoji: "🏹",
    category: "military",
    epoch_required: "Industrial Age",
    description: "Produces firearms and munitions for troops.",
    cost: { res_iron: 250, res_gold: 150, currency: 1000 },
    workforce: 3,
    benefits: { unit_power: 40, manufacturing: 25, defense_level: 15 },
    populationCap: null,
  },
  {
    id: "tank_factory",
    name: "Tank Factory",
    emoji: "🚜",
    category: "military",
    epoch_required: "Modern Age",
    description: "Produces heavy armor and tanks.",
    cost: { res_iron: 400, res_gold: 300, currency: 2500 },
    workforce: 4,
    benefits: { unit_power: 70, defense_level: 35 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "nuclear_arsenal",
    name: "Nuclear Arsenal",
    emoji: "💣",
    category: "military",
    epoch_required: "Information Age",
    description: "Stores nuclear weapons. Massive deterrent.",
    cost: { res_gold: 2000, currency: 8000 },
    workforce: 2,
    benefits: { unit_power: 150, defense_level: 100 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "biohazard_lab",
    name: "Biohazard Lab",
    emoji: "🧬",
    category: "military",
    epoch_required: "Space Age",
    description: "Advanced biological weapons research.",
    cost: { res_gold: 2500, currency: 6000 },
    workforce: 3,
    benefits: { unit_power: 80, defense_level: 45 },
    populationCap: null,
    uniqueMax: 1,
  },

  // ── MORE CIVILIAN/RESEARCH ─────────────────────────────────────────────────
  {
    id: "science_academy",
    name: "Science Academy",
    emoji: "🔭",
    category: "civilian",
    epoch_required: "Industrial Age",
    description: "Advanced research center. Generates +40 TP per tick.",
    cost: { res_gold: 400, currency: 2000 },
    workforce: 2,
    benefits: { tpBonus: 40, stability: 6 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "genetics_lab",
    name: "Genetics Lab",
    emoji: "🧪",
    category: "civilian",
    epoch_required: "Space Age",
    description: "Genetic engineering and biotech research.",
    cost: { res_gold: 1200, currency: 4000 },
    workforce: 3,
    benefits: { tpBonus: 60, gdp: 300, public_trust: 0.15 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "space_agency",
    name: "Space Agency",
    emoji: "🛸",
    category: "civilian",
    epoch_required: "Digital Age",
    description: "Space exploration and satellite technology.",
    cost: { res_gold: 1800, currency: 5500 },
    workforce: 4,
    benefits: { tpBonus: 50, gdp: 400, public_trust: 0.2 },
    populationCap: null,
    uniqueMax: 1,
  },
  {
    id: "energy_plant",
    name: "Energy Plant",
    emoji: "⚡",
    category: "civilian",
    epoch_required: "Industrial Age",
    description: "Provides power infrastructure. Boosts all production.",
    cost: { res_iron: 300, res_gold: 200, currency: 1500 },
    workforce: 3,
    benefits: { gdp: 300, manufacturing: 40 },
    populationCap: null,
    uniqueMax: 2,
  },
  {
    id: "water_treatment",
    name: "Water Treatment Plant",
    emoji: "💧",
    category: "civilian",
    epoch_required: "Modern Age",
    description: "Ensures clean water access. Boosts health and stability.",
    cost: { res_iron: 150, res_stone: 100, currency: 800 },
    workforce: 2,
    benefits: { stability: 10, public_trust: 0.12 },
    populationCap: null,
    uniqueMax: 2,
  },
  {
    id: "waste_management",
    name: "Waste Management Facility",
    emoji: "♻️",
    category: "civilian",
    epoch_required: "Modern Age",
    description: "Manages pollution and waste. Improves stability.",
    cost: { res_stone: 120, currency: 600 },
    workforce: 2,
    benefits: { stability: 8, public_trust: 0.08 },
    populationCap: null,
    uniqueMax: 1,
  },

  // ── OIL INFRASTRUCTURE ────────────────────────────────────────────────────
  {
    id: "oil_reserve_small",
    name: "Small Oil Reserve",
    emoji: "🛢️",
    category: "civilian",
    epoch_required: "Industrial Age",
    description: "Strategic petroleum reserve. Stores 25,000 oil units, protected from price volatility.",
    cost: { res_stone: 200, res_iron: 150, currency: 800 },
    workforce: 1,
    benefits: { stability: 2 },
    populationCap: null,
    uniqueMax: 3,
  },
  {
    id: "oil_reserve_national",
    name: "National Oil Reserve",
    emoji: "🏭",
    category: "government",
    epoch_required: "Modern Age",
    description: "Large strategic oil reserve storing 100,000 oil units. Shields economy from fuel price shocks.",
    cost: { res_iron: 400, res_gold: 300, currency: 3000 },
    workforce: 2,
    benefits: { stability: 5, gdp: 150 },
    populationCap: null,
    uniqueMax: 2,
  },
  {
    id: "refinery",
    name: "Oil Refinery",
    emoji: "⚗️",
    category: "civilian",
    epoch_required: "Industrial Age",
    description: "Converts crude oil into gasoline and diesel. 1 oil → 0.6 gasoline + 0.4 diesel per tick.",
    cost: { res_iron: 250, res_stone: 200, res_gold: 150, currency: 1500 },
    workforce: 3,
    benefits: { gdp: 200, manufacturing: 20 },
    populationCap: null,
    uniqueMax: 3,
  },
  {
    id: "gas_station",
    name: "Gas Station",
    emoji: "⛽",
    category: "civilian",
    epoch_required: "Industrial Age",
    description: "Distributes fuel to citizens, boosting transportation efficiency and GDP.",
    cost: { res_iron: 80, res_stone: 60, currency: 400 },
    workforce: 1,
    benefits: { gdp: 100, stability: 2 },
    populationCap: null,
    uniqueMax: 5,
  },

  // ── WAREHOUSES ─────────────────────────────────────────────────────────────
  {
    id: "warehouse_small",
    name: "Small Warehouse",
    emoji: "🏚️",
    category: "civilian",
    epoch_required: "Stone Age",
    description: "Adds 5,000 storage capacity per resource. Protects reserves from war and price volatility.",
    cost: { res_wood: 80, res_stone: 60, currency: 150 },
    workforce: 1,
    benefits: { stability: 1 },
    populationCap: null,
  },
  {
    id: "warehouse_industrial",
    name: "Industrial Warehouse",
    emoji: "🏭",
    category: "civilian",
    epoch_required: "Industrial Age",
    description: "Adds 25,000 storage capacity per resource. Immune to global price changes inside.",
    cost: { res_iron: 150, res_stone: 200, currency: 800 },
    workforce: 2,
    benefits: { stability: 2 },
    populationCap: null,
    uniqueMax: 3,
  },
  {
    id: "warehouse_strategic",
    name: "Strategic Reserve Complex",
    emoji: "🏗️",
    category: "government",
    epoch_required: "Modern Age",
    description: "Adds 100,000 storage capacity. Full immunity to war capture and price shocks.",
    cost: { res_iron: 400, res_gold: 300, currency: 3000 },
    workforce: 3,
    benefits: { stability: 4, public_trust: 0.05 },
    populationCap: null,
    uniqueMax: 2,
  },
  ];

export const BUILDING_MAP = Object.fromEntries(BUILDINGS.map(b => [b.id, b]));

/**
 * Epoch advancement requirements — 26% compounded scaling rule
 * stability_min: minimum % required to advance (enforced in TechTreePanel)
 */
export const EPOCH_REQUIREMENTS = {
  "Stone Age": {
    tp: 50,
    population: 100,
    stability_min: 70,
    buildings: { school: 1 },
    resources: { res_wood: 100, res_stone: 80 },
    treasury: 200,
  },
  "Bronze Age": {
    tp: 130,
    population: 80,
    stability_min: 70,
    buildings: { school: 1, capital: 1 },
    resources: { res_wood: 300, res_stone: 200, res_gold: 80 },
    treasury: 550,
  },
  "Iron Age": {
    tp: 200,
    population: 130,
    stability_min: 70,
    buildings: { school: 1, barracks: 1 },
    resources: { res_iron: 100, res_stone: 200, res_gold: 100 },
    treasury: 900,
  },
  "Classical Age": {
    tp: 320,
    population: 200,
    stability_min: 72,
    buildings: { school: 2, courthouse: 1 },
    resources: { res_stone: 400, res_gold: 150 },
    treasury: 1500,
  },
  "Medieval Age": {
    tp: 500,
    population: 300,
    stability_min: 72,
    buildings: { school: 2, hospital: 1, barracks: 1 },
    resources: { res_stone: 400, res_iron: 200, res_gold: 200 },
    treasury: 2500,
  },
  "Renaissance Age": {
    tp: 750,
    population: 450,
    stability_min: 74,
    buildings: { university: 1, market: 2, capital: 1 },
    resources: { res_gold: 300, res_stone: 400 },
    treasury: 4000,
  },
  "Industrial Age": {
    tp: 1100,
    population: 700,
    stability_min: 75,
    buildings: { university: 1, capital: 1, military_foundry: 1 },
    resources: { res_gold: 600, res_iron: 400 },
    treasury: 8000,
  },
  "Modern Age": {
    tp: 1600,
    population: 1100,
    stability_min: 76,
    buildings: { university: 2, capital: 1, air_base: 1 },
    resources: { res_gold: 1200, res_oil: 500 },
    treasury: 15000,
  },
  "Digital Age": {
    tp: 2300,
    population: 1500,
    stability_min: 78,
    buildings: { university: 2, intelligence_agency: 1 },
    resources: { res_gold: 2000 },
    treasury: 25000,
  },
  "Information Age": {
    tp: 3300,
    population: 2200,
    stability_min: 79,
    buildings: { university: 3, capital: 1 },
    resources: { res_gold: 4000 },
    treasury: 40000,
  },
  "Space Age": {
    tp: 5000,
    population: 3000,
    stability_min: 80,
    buildings: { university: 3, space_agency: 1 },
    resources: { res_gold: 7000 },
    treasury: 65000,
  },
  // Galactic Age is final — no requirements
};