// Deep-dive content for all tutorial sections
export const DEEP_DIVES = {
  "#tutorial-button": {
    title: "Using the Tutorial & Help System",
    screenshot: { label: "Tutorial Button Location", desc: "The 📖 Tutorial button lives in the top navigation bar. Click it at any time to reopen this guide.", visual: ["📖 Tutorial  ← top bar", "Opens full guide overlay", "Search bar inside finds any topic", "No progress is lost when you close it"] },
    content: `**How the Tutorial Works**\n\nThe tutorial is divided into 13 topic sections, each with multiple lessons. You can:\n\n- Browse all topics from the home screen\n- Use the search bar to find any keyword\n- Jump to any lesson step directly\n- Expand "Read More" sections for deep-dive content\n- Close and reopen at any time — your place is not saved intentionally so you can always restart a section\n\n**Deep Dives (📖 Read More):**\nMany lesson steps have an expandable "Read More" section providing full mechanical detail, tables, formulas, and extra context. These are optional — the core lesson is always self-contained.\n\n**Tips (💡):**\nEach lesson ends with practical tips. These are non-spoiler hints from experienced players.\n\n**Mobile Navigation:**\nOn mobile, swipe left/right on the lesson content to navigate steps.`,
    tips: ["The search bar at the top of the tutorial home screen finds any topic instantly.", "You can re-read any section at any time — nothing locks.", "The tutorial covers every major system. If something feels confusing, there's a section for it."]
  },
  "#dashboard-layout": {
    title: "Dashboard Layout Deep Dive",
    screenshot: { label: "Full Dashboard Layout", desc: "The dashboard uses a 3-column bento grid on desktop. On mobile it stacks vertically with a navigation bar at the bottom.", visual: ["[LEFT COLUMN]  Nation Stats + Resource Cards", "[CENTER]        World Map + World Chat", "[RIGHT COLUMN] Nation Metrics + Stock Ticker", "─────────────────────────────────────────", "Mobile: Stacked | Bottom nav bar scrolls"] },
    content: `**The Three-Column Layout**\n\n**Left Column — Nation Stats Panel:**\nYour primary nation data: epoch, population, treasury, GDP, resources, tech level, and allies. This is your "at a glance" view of national health.\n\n**Center Column — World Map & Chat:**\nThe interactive hex world map occupies the center. Below or alongside it (depending on screen size) is the World Chat interface with Global/Allies/System channels and the Activity Ledger.\n\n**Right Column — Metrics & Market:**\nNation Metrics Panel (stability, manufacturing, defense, unit power) plus the live Stock Ticker feed scrolling all price movements.\n\n**Header Bar:**\nAll action buttons: Issue Stock, Tech Tree, Research, Manage, Workers, Exchange, Government, Global News, Build, Marketplace, Profile, Tutorial.\n\n**Mobile Layout:**\nOn mobile the three columns stack. The bottom scrollable bar contains the action buttons. Swipe horizontally to access all buttons.`,
    tips: ["Bookmark the Dashboard — you'll return here after every other action.", "On mobile, the left swipe reveals Nation Stats; right swipe reveals Metrics.", "The header button bar is always accessible regardless of which panel you're viewing."]
  },
  "#notifications": {
    title: "Notification System Guide",
    screenshot: { label: "Notification Bell", desc: "The bell icon in the header shows an unread count badge. Click to expand the notification dropdown.", visual: ["🔔 (3)  ← unread count badge", "─────────────────────────────", "🔴 War declared by Iron Dominion!", "🟡 Stock AXG dropped 12%", "🟢 Tech Breakthrough: Steam Power unlocked"] },
    content: `**Types of Notifications**\n\n**Danger (Red):**\n- War declared on you\n- Attack received — buildings damaged\n- Stock market crash in one of your holdings\n- Loan default warning\n\n**Warning (Yellow/Amber):**\n- Stock price decline alerts\n- Resource nearing storage cap\n- Stability falling below 40\n- Ally under attack\n\n**Info (Blue):**\n- Lend-lease received\n- Trade route proposal pending\n- Alliance offer received\n\n**Success (Green):**\n- Tech breakthrough completed\n- Epoch advance available\n- Trade agreement accepted\n\n**Notification Persistence:**\nNotifications remain until marked as read. Older notifications stack below newer ones. Critical notifications (war, crash) also appear as toast banners on screen.`,
    tips: ["Check notifications at the start of every session to catch offline events.", "Red notifications are time-sensitive — act on war and crash notifications immediately.", "Notifications for stock drops help you react before price falls further."]
  },
  "#influence-points": {
    title: "Influence Points System",
    screenshot: { label: "Influence Points Display", desc: "Influence Points (IP) shown in the Government/Policy panel. Current IP, regen rate, and available diplomatic actions listed.", visual: ["🎖️ Influence Points: 85 / 200", "Regen: +5/tick  (base)", "National Library: +2/tick bonus", "─────────────────────────────", "[ /spy @Nation  — 20 IP ]", "[ /ally @Nation — 10 IP ]"] },
    content: `**What Are Influence Points?**\n\nInfluence Points (IP) are your diplomatic currency. They're spent on chat commands and diplomatic actions.\n\n**IP Costs:**\n| Action | Cost |\n|---|---|\n| /trade @Nation | 5 IP |\n| /ally @Nation | 10 IP |\n| /peace @Nation | 5 IP |\n| /sanction @Nation | 15 IP |\n| /spy @Nation | 20 IP |\n| Publish Propaganda | 20 IP |\n| /war @Nation | 0 IP (free) |\n\n**IP Generation:**\n- Base: +5/tick passive\n- National Library: +2/tick\n- Palace: +3/tick\n- Advisor upgrades: additional bonuses\n\n**IP Cap:**\nMaximum IP is determined by your government buildings. Build more governance structures to raise the cap.\n\n**Strategy:**\nSave IP for spy reports (20 IP) before major diplomatic moves. Don't waste IP on /trade proposals that are likely to be rejected.`,
    tips: ["Always have 20+ IP in reserve for emergency spy reports before a conflict.", "National Library and Palace together give +5/tick IP bonus — the best passive diplomatic investment.", "If you're not actively using IP, it simply accumulates. Don't rush spending it."]
  },
  "#lend-lease": {
    title: "Lend-Lease & Aid System",
    screenshot: { label: "Lend-Lease Modal", desc: "Click 'Send Aid' on any nation's profile to open the Lend-Lease panel. Choose resource type and amount. A confirmation shows the full transfer cost.", visual: ["🤝 Send Aid to: Principality of Auros", "Type: [ Credits ▼ ]  Amount: [  200  ]", "─────────────────────────────────────", "Cost: 200 Credits from your treasury", "[ Send Aid → ]"] },
    content: `**Lend-Lease & Foreign Aid**\n\nYou can transfer Credits, Resources, or Tech Points to any nation at any time — no prerequisites.\n\n**Why Send Aid?**\n- Build diplomatic goodwill before proposing a formal alliance\n- Support an ally who is losing a war\n- Help a new nation survive early game (builds long-term trading relationships)\n- Signal peaceful intentions to a potential aggressor\n\n**Aid Types:**\n| Type | Use Case |\n|---|---|\n| Credits | Stabilize a bankrupt ally, fund a joint project |\n| Resources | Emergency food/wood during a crisis |\n| Tech Points | Help an ally advance epochs faster |\n\n**Cost:**\nYou pay the full value of what you send. There is no exchange rate bonus — aid is pure goodwill.\n\n**Visibility:**\nAll aid transfers are logged in the Global Activity Ledger. Other players can see you are supporting a nation.`,
    tips: ["Small, repeated aid packages build trust faster than one large transfer.", "Aid before alliance is a classic diplomatic move — don't skip it.", "Sending resources during a famine is one of the most powerful diplomatic gestures in the game."]
  },
  "#peace-deals": {
    title: "Peace Negotiations Guide",
    screenshot: { label: "Peace Proposal Interface", desc: "Access via Nation Interaction menu while at war. Choose terms: unconditional peace or resource-transfer peace.", visual: ["⚖️ Propose Peace with Iron Dominion", "Terms: [ Unconditional ▼ ]", "─ OR ─", "Demand: [ 200 Credits ] from them", "Offer: [ 50 Stone ] as goodwill gesture", "[ Send Proposal → ]"] },
    content: `**How Peace Works**\n\n**Who Can Propose:**\nEither party can propose peace at any time during the war. There's no cooldown.\n\n**Peace Terms:**\n- Unconditional: War ends, no transfers. Good when both nations want out quickly.\n- Conditional: Include resource, credit, or territory transfers as part of the deal.\n\n**The Other Side Must Accept:**\nProposed terms appear in the target nation's notification feed. They can accept, reject, or counter-propose.\n\n**After Peace:**\n- Both nations gain +1 stability/tick for several ticks (peace dividend)\n- War-broken trade routes can be reactivated\n- Both nations remain independent — no territory changes unless agreed\n\n**War Auto-Expiry:**\nIf neither party negotiates, war auto-expires after ~3.5 real hours with no additional consequences beyond accumulated tick damage.\n\n**Strategic Timing:**\nThe best time to offer peace is after landing 2–3 successful attacks — you've demonstrated strength, and peace locks in your advantage before the tide turns.`,
    tips: ["Offering peace from a position of strength gets better terms than waiting until both sides are exhausted.", "Unconditional peace is faster to negotiate. Use it when time matters more than gains.", "A peace treaty records in the Global Chronicles — it signals maturity and stability to investors."]
  },
  "#stability-deep": {
    title: "Stability System Deep Dive",
    screenshot: { label: "Stability Indicator", desc: "Stability shown as a progress bar in the Metrics panel with color coding and a trend arrow.", visual: ["⚖️ Stability: 72  ↑  [████████░░] ✅ Healthy", "⚖️ Stability: 38  ↓  [████░░░░░░] ⚠️ At Risk", "⚖️ Stability: 14  ↓↓ [██░░░░░░░░] 🔴 CRISIS"] },
    content: `**Why Stability Is Everything**\n\nStability (0–100) is the single most important number in the game. Nearly every other system references it.\n\n**What Stability Affects:**\n- GDP growth rate (below 50: GDP drag)\n- Population growth (below 30: stops growing)\n- Stock prices (your companies)\n- Public Trust decay/growth\n- Dilemma frequency (more dilemmas when low)\n- War outcome calculations\n\n**Stability Sources (gains per tick):**\n- Healthcare Policy: +5/tick\n- Town Hall building: +2/tick\n- Palace building: +3/tick\n- Peace treaty aftermath: +1/tick\n- Good dilemma choices: +1 to +5 (one-time)\n\n**Stability Losses (per tick):**\n- Active war: -1/tick\n- Famine: -3/tick per famine event\n- Martial Law (prolonged): -side effects\n- Ignored dilemmas: -2 to -8 (one-time)\n- Bankruptcy: -5/tick\n\n**Recovery Rate:**\nWithout active crisis, stability naturally drifts toward 50 if no sources push it up or down. Active Healthcare Policy is the fastest stabilizer.`,
    tips: ["Never let stability drop below 40 without a recovery plan in place.", "The Town Hall is the cheapest permanent stability source — build it early.", "Stability below 25 during war is an emergency. Offer peace immediately."]
  },


  "#clock": {
    title: "Understanding the Game Clock",
    screenshot: { label: "Time Conversion", desc: "One real-world minute = 1 game tick = 1 in-game day. The simulation runs continuously whether you're online or not.", visual: ["🕐 1 Real Min", "→", "⏱ 1 Game Tick", "→", "📅 1 Game Day", "→", "📆 30 ticks = 1 Month"] },
    content: `**How time works**\n\nEvery 60 real-world seconds the simulation fires one tick. Each tick = one in-game day.\n\n• 60 real seconds = 1 game day\n• ~7 real minutes = 1 game week\n• ~30 real minutes = 1 game month\n• ~6 real hours = 1 game year\n\nThe simulation runs at the same rate for everyone — logging in more often doesn't give extra ticks. Even when you're offline, war penalties, famine, loan interest, and Tech Points all accumulate.\n\n**Tick Delay on Startup:**\nThe Resource Engine waits 20 seconds after loading before its first tick. This prevents stale-data calculations while entities load.`,
    tips: ["You don't need to be online every minute — engines keep running in the background.", "War penalties and famine tick continuously even offline. Always leave your nation in a stable state.", "Log in daily to manage Tech Points and loan interest."]
  },
  "#nav": {
    title: "Top Navigation — Full Button Reference",
    screenshot: { label: "Dashboard Header Buttons", desc: "All quick-action buttons live in the header bar (desktop) or scrollable bottom bar (mobile).", visual: ["📈 Issue Stock", "🧬 Tech Tree", "🔬 Research", "📊 Manage", "👷 Workers", "📊 Exchange", "🏛️ Gov't", "🌐 News", "🏗️ Build", "🏪 Market", "👤 Profile", "📖 Tutorial"] },
    content: `**Button Reference**\n\n| Button | Opens | What It's For |\n|---|---|---|\n| Issue Stock | IPO listing form | List a new company on the exchange |\n| Tech Tree | Tech unlock panel | Spend Tech Points on upgrades |\n| Research | Advanced research queue | Queue multi-tick research projects |\n| Manage | Budget & tax sliders | Set tax rates and spending split |\n| Workers | Workforce assignment | Assign citizens to production roles |\n| Exchange | Global stock exchange | Buy/sell shares in all nations |\n| Government | Policy toggles & news | Toggle national policies |\n| Global News | World Chronicles | Read global newspaper |\n| Build | Construction Hub | Build and upgrade buildings |\n| Marketplace | Trade & commodities | Buy/sell resources, set trade routes |\n| Profile | National identity & war room | War, diplomacy, nation wiki |\n| Tutorial | This guide | Reopen at any time |\n\nMobile: Swipe the bottom bar horizontally to access all buttons.`,
    tips: ["'Manage' is the most important daily button — it controls your entire economic policy.", "Workers must be reassigned manually when population grows.", "Exchange = stocks. Marketplace = raw resources. They are different pages."]
  },
  "#epochs": {
    title: "Epoch Progression Guide",
    screenshot: { label: "Epoch Progress Bar", desc: "Nation Stats shows your current Epoch in a cyan badge, with a glowing progress bar toward the next epoch.", visual: ["🪨 Stone", "→", "🥉 Bronze", "→", "⚔️ Iron", "→", "🏛️ Classical", "→", "🏰 Medieval", "→", "⚙️ Industrial", "→", "💻 Digital", "→", "🌌 Galactic"] },
    content: `**The 12 Epochs**\n\nAdvancing requires: minimum Tech Points banked + all prerequisite techs unlocked.\n\n**Key Epoch Unlocks:**\n- Stone → Bronze: Bronze buildings, early military, first markets\n- Bronze → Iron: Iron Miners, iron construction, early diplomacy\n- Iron → Classical: Trade routes, universities, government buildings\n- Classical → Medieval: Walls, castles, guilds, mercantile economy\n- Medieval → Renaissance: Banking, printing press, advanced culture\n- Renaissance → Industrial: Factories, oil drilling, stock exchanges\n- Industrial → Modern: Global markets, corporate law, mass production\n- Modern → Digital: Internet, cyber infrastructure, digital currency\n- Digital → Information: AI research, data centers, information warfare\n- Information → Space: Orbital infrastructure, satellite defense\n- Space → Galactic: The final epoch — interstellar dominance\n\n**Cost Scaling:** Each epoch increases all construction costs ~15% and resource consumption ~10%.`,
    tips: ["Don't rush epochs — a well-built Stone Age economy beats a broke Renaissance nation.", "Epoch advances trigger a global announcement. Other players will know.", "The Industrial Age is the biggest transition — it unlocks stock exchanges and oil."]
  },
  "#population": {
    title: "Population Mechanics",
    screenshot: { label: "Population Display", desc: "Population shows as a number in Nation Stats with a trend arrow. Below it, Housing Capacity shows the hard cap.", visual: ["👥 Population: 47  ↑", "🏠 Housing Capacity: 50", "⚠️ Near cap — Build Housing!"] },
    content: `**Growth Formula**\n\nEach tick, +1 pop chance (30%) if ALL are true:\n- Net food production > 0\n- Current population < Housing Capacity\n- Stability >= 30\n\n**Population Decline:**\n- Famine (food = 0): 50% chance -1 pop/tick, -3 stability, -0.05 trust\n- Civil unrest (stability < 20): 20% chance -1 pop/tick\n- War: 15% chance -1 pop/tick\n\n**Why population matters:**\n- More pop = more workers to assign\n- Citizens generate passive tech points (0.001 per citizen/tick)\n- Tax revenue scales with population\n- GDP formula uses population as a multiplier\n\n**Housing Capacity:**\n- Base: 20\n- Each Housing building: +10\n- Each City founded: additional capacity`,
    tips: ["Keep 5+ housing slots free — sudden population bursts can overflow your capacity.", "Wars kill population passively. A long war with 50 citizens can drop you to 30.", "Cities provide their own housing capacity separate from national housing buildings."]
  },
  "#treasury": {
    title: "Treasury Management",
    screenshot: { label: "Treasury Display", desc: "Treasury (Credits) is shown prominently in Nation Stats with a trend indicator and income breakdown.", visual: ["💰 Treasury: 1,247 Credits  ↑", "📈 Tax: +28/tick", "🚢 Trade: +12/tick", "🏗️ Upkeep: -6/tick", "→ Net: +34/tick"] },
    content: `**Treasury Income Sources**\n\n1. Income Tax — % of citizen wages\n2. Sales Tax — % on marketplace transactions\n3. Corporate Tax — % of domestic company profits\n4. Tariffs — % on imports via trade routes\n\n**Treasury Expenses:**\n- Military & Education spending %\n- Building upkeep (auto-deducted per tick)\n- Loan repayments (if active)\n\n**The Bankruptcy Cascade:**\nIf treasury hits 0 while expenses continue:\n- Stability -5/tick while insolvent\n- Public trust drops rapidly\n- Stock prices of your companies fall\n- Creditors may trigger loan defaults\n\n**Safe Reserve Rule:** Keep at least 10× your per-tick expenses as a buffer.`,
    tips: ["Corporate tax is the cleanest revenue source — it doesn't directly hurt citizen happiness.", "Building upkeep is automatic and non-negotiable. Don't build more than your treasury can sustain.", "If going negative, cut military spending first — lowest immediate impact on stability."]
  },
  "#gdp": {
    title: "GDP Formula Deep Dive",
    screenshot: { label: "GDP & Growth Indicators", desc: "GDP in Nation Stats shows current value with a tick-over-tick direction arrow. The Metrics Panel shows the full economic breakdown.", visual: ["📊 GDP: 2,841 Credits  ↑ +1.2%/tick", "🏭 Manufacturing Index: 67", "💹 Money Supply: 5,200", "📈 Inflation: 3.2%  ✅"] },
    content: `**The GDP Formula**\n\nBase × Manufacturing × Trade Modifier × Stability × Tech Multiplier × Inflation Penalty\n\n**Components:**\n- Base GDP: Starts at 500, scales with population and buildings\n- Manufacturing Index: 0–100 score from industrial workers and factories\n- Trade Modifier: Trade surplus adds up to +15% GDP; deficits subtract\n- Stability Modifier: Stability < 50 applies a GDP drag\n- Tech Multiplier: Each epoch adds ~8% GDP efficiency\n- Inflation Penalty: Inflation above 8% reduces GDP growth rate\n\n**GDP Growth Drivers:**\n- Build Factories and Industrial Zones\n- Maintain active Trade Routes with surplus\n- Keep Stability above 60\n- Advance epochs\n- Issue IPO'd companies (Market Cap feeds National Wealth)\n\n**Tax Revenue:** Approximately: GDP × (Income + Sales + Corporate Rates) / 100 × 0.25`,
    tips: ["Manufacturing Index is the single biggest GDP lever in mid-game. Invest in factories early.", "GDP grows exponentially once all multipliers work together.", "A trade surplus of even +50 credits/tick compounds dramatically over a session."]
  },
  "#resources": {
    title: "Resource Production Guide",
    screenshot: { label: "Resource Cards", desc: "Nation Stats shows each resource as a colored card with current stock and production rate.", visual: ["🪵 Wood: 342  +12/tick", "🪨 Stone: 215  +8/tick", "🥇 Gold: 89  +4/tick", "⚙️ Iron: 0  (Iron Age+)", "🛢️ Oil: 0  (Industrial+)", "🌾 Food: 540  +6/tick net"] },
    content: `**Resource Overview**\n\n| Resource | Worker | Rate | Epoch |\n|---|---|---|---|\n| Food | Farmers/Hunters/Fish | 8/3-7/6 | Always |\n| Wood | Lumberjacks | 5/worker | Always |\n| Stone | Quarry Workers | 4/worker | Always |\n| Gold | Miners | 2/worker | Always |\n| Iron | Iron Miners | 3/worker | Iron Age+ |\n| Oil | Oil Engineers | 6/worker | Industrial+ |\n\nTech Multiplier: Each epoch adds 8% to all production. At Industrial Age (epoch 6): ×1.48.\n\n**Storage Caps:**\n- Natural cap: 6,000 units per resource\n- Small Warehouse: +5,000\n- Industrial Warehouse: +25,000\n- Strategic Warehouse: +100,000`,
    tips: ["Iron is required for most mid-game military and industrial buildings. Start mining immediately at Iron Age.", "Oil Engineers produce 6/tick — the resource is used for factories and advanced units.", "Food is consumed every tick regardless. If net food is negative, you're burning reserves."]
  },
  "#taxes": {
    title: "Tax Strategy Guide",
    screenshot: { label: "Tax Sliders — Budget Panel", desc: "The Manage/Budget panel shows four slider bars with a live revenue estimator.", visual: ["Income Tax:    [████░░░░░░] 15%", "Sales Tax:     [███░░░░░░░] 8%", "Corporate Tax: [████░░░░░░] 12%", "Tariff:        [██░░░░░░░░] 5%", "≈ Revenue: +28 Credits/tick"] },
    content: `**Tax Rate Effects**\n\n**Income Tax (0–40%):**\n- Revenue: High per-citizen contribution\n- Side effects: Above 25% reduces Public Trust, can trigger civil unrest\n- Best range: 10–20%\n\n**Sales Tax (0–25%):**\n- Revenue: Scales with marketplace activity\n- Side effects: Discourages trading above 15%\n- Best range: 5–12%\n\n**Corporate Tax (0–35%):**\n- Revenue: Scales with company market caps\n- Side effects: Above 25% begins reducing your stock valuations\n- Best range: 10–18%\n\n**Tariff (0–30%):**\n- Revenue: Only applies to imports\n- Side effects: Above 15% invites diplomatic friction\n- Best range: 3–10%\n\n**Government Type Defaults:**\n- Democracy: Balanced (15/8/12/5)\n- Communist State: Income 25%, Corporate 5%\n- Technocracy: Income 16%, Corporate 14%`,
    tips: ["Never raise income tax above 30% — civil unrest events cost more than the revenue gained.", "If you have lots of IPO'd companies, corporate tax is your most efficient lever.", "Tariffs hurt your trade partners. Keep them low on allies."]
  },
  "#workers": {
    title: "Worker Role Reference",
    screenshot: { label: "Workforce Panel", desc: "Shows all roles with +/- buttons. Summary bar shows Total Population vs Total Assigned. Epoch-locked roles appear grayed out.", visual: ["👥 Population: 24  |  Assigned: 21  |  Unassigned: 3", "🌾 Farmers: 4  [−][+]  → +32 Food/tick", "🪵 Lumberjacks: 3  [−][+]  → +15 Wood/tick", "🔬 Researchers: 3  [−][+]  → +12 TP/tick"] },
    content: `**All Worker Roles**\n\n| Role | Produces | Base Rate |\n|---|---|---|\n| Farmers | Food | 8/tick |\n| Hunters | Food | 3–7/tick random |\n| Fishermen | Food | 6/tick |\n| Lumberjacks | Wood | 5/tick |\n| Quarry Workers | Stone | 4/tick |\n| Miners (Gold) | Gold | 2/tick |\n| Iron Miners | Iron | 3/tick Iron Age+ |\n| Oil Engineers | Oil | 6/tick Industrial+ |\n| Soldiers | Military Power | — |\n| Researchers | Tech Points | variable |\n| Industrial Workers | Manufacturing Index | — |\n| Builders | Construction Speed | — |\n\n**Early Game Priority:**\nFarmers (2–3 per 10 pop) + Lumberjacks (2–3) + 1–2 Researchers. As you grow, shift toward Miners and Industrial Workers.`,
    tips: ["Researchers have diminishing returns above ~5 unless you've built Universities.", "Industrial Workers boost Manufacturing Index which feeds into GDP.", "Builders speed up construction — valuable when mid-project on expensive buildings."]
  },
  "#food": {
    title: "Food System Guide",
    screenshot: { label: "Food Resource Card", desc: "The Food card shows current reserves and net production. A warning icon appears when net food is negative.", visual: ["🌾 Food: 1,240 units", "Consumption: 28/tick  (pop × 1.2)", "Production: 34/tick", "Net: +6/tick  ✅ Surplus"] },
    content: `**The Food Economy**\n\nConsumption per tick = Population × 1.2\n\nWith 20 citizens: 24 food consumed per tick.\n\n**Production sources:**\n- Farmers: 8 × tech_mult per worker\n- Hunters: (3–7) × tech_mult (random)\n- Fishermen: 6 × tech_mult per worker\n- Granary building: additional bonus\n\n**Famine Sequence:**\n1. Net food < 0 → reserves depleting (yellow warning)\n2. Reserves hit 0 → FAMINE begins (red)\n3. Each famine tick: 50% chance -1 pop, -3 stability, -0.05 trust\n4. Continued famine can collapse small nations in under 10 ticks\n\n**Preventing Famine:**\n- Keep (Farmers × 8 × tech_mult) > (Population × 1.2) at all times\n- Maintain 200+ food reserves as buffer\n- Build a Granary to triple your food reserve cap`,
    tips: ["Hunters add randomness. Use Farmers as your base food source.", "Fishermen produce 6/tick — excellent if you have coastal hexes.", "Before declaring war, ensure 500+ food reserves. Wars force workers into soldiers."]
  },
  "#resource-workers": {
    title: "Resource Worker Breakdown",
    screenshot: { label: "Worker Production Preview", desc: "Hovering a worker role shows exact production per tick with tech multiplier applied.", visual: ["🪵 Lumberjack × 3", "Base: 5/tick each", "Tech (Bronze Age): ×1.08", "Lumberyard Lvl 2: +20%", "→ Total: ~19 Wood/tick"] },
    content: `**Production Rate Formula**\n\nOutput = Workers × Base Rate × (1 + EpochIndex × 0.08)\n\n**Example at Industrial Age (epoch 6, mult 1.48):**\n- 3 Lumberjacks → 3 × 5 × 1.48 = 22 wood/tick\n- 2 Iron Miners → 2 × 3 × 1.48 = 8 iron/tick\n- 1 Oil Engineer → 1 × 6 × 1.48 = 8 oil/tick\n\n**Building Bonuses:**\n- Lumberyard: +20% to wood\n- Quarry: +20% to stone\n- Gold Mine: +20% to gold\n- Factory: Boosts Industrial Workers' manufacturing output\n\n**Priority by Era:**\n- Early (Stone-Bronze): Food + Wood + Stone\n- Mid (Iron-Classical): Gold + Iron\n- Late (Industrial+): Oil + Industrial Workers`,
    tips: ["Stone is consumed heavily during construction phases. Stock up before big build projects.", "Gold doesn't deplete passively — it's safe to stockpile for trading.", "Oil is the most strategic resource in Industrial Age. Control it and you control the energy economy."]
  },
  "#research-system": {
    title: "Research System Guide",
    screenshot: { label: "Research Panel", desc: "Shows active research with a progress bar (0–100%), required points, current points, and estimated ticks to completion.", visual: ["🔬 Agriculture 2.0", "Progress: ████████░░ 78%", "Points: 78 / 100", "Est. 2 ticks remaining"] },
    content: `**Two Research Systems**\n\n**1. Tech Tree (instant unlocks):**\n- One-time Tech Point payment\n- Effect is immediate upon purchase\n\n**2. Research Panel (advanced projects):**\n- Continuous TP investment over multiple ticks\n- Researchers generate TP → invested into active project\n- Completion triggers global announcement if a Breakthrough\n\n**Tech Point Generation:**\nTP/tick = (Schools×1 + Universities×4) + (Pop×0.001) + (EducationSpending×0.1) + Other Building Bonuses\n\n**Storage Cap:**\nMax TP = 500 + Schools×1000 + Colleges×3000 + Universities×6000\n\nIf TP hits cap, excess is wasted. Build more education buildings.`,
    tips: ["Always have a research project queued. Idle Tech Points are wasted production.", "Global Breakthroughs give the first discoverer a permanent bonus AND cause rivals to pay a diffusion penalty.", "Universities generate 4× more TP than Schools — the single best mid-game investment."]
  },
  "#military": {
    title: "Military System Guide",
    screenshot: { label: "Military Stats", desc: "Military stats in Metrics panel show Unit Power (offense) and Defense Level (defense) as progress bars.", visual: ["⚔️ Unit Power:    [████████░░] 78", "🛡️ Defense Level: [███████░░░] 68", "🔴 AT WAR with: Republic of Valdorn"] },
    content: `**Military Overview**\n\n**Unit Power — Offensive strength:**\n- Base: 10\n- +2 per Soldier assigned\n- +bonus from Barracks, Arsenal buildings\n\n**Defense Level — Defensive strength:**\n- Base: 10\n- +bonus from Wall, Fortress, Castle buildings\n- +1 per military tech unlocked\n\n**During War (every tick):**\n- Your Stability -1\n- 15% chance Population -1\n\n**Attack Formula:**\nDamage = (Unit Power / Defense Level) × Base Damage × Random(0.8–1.2)\n\n**War Duration:**\nAuto-expires after ~3.5 real hours (1 in-game week). Peace can also be negotiated at any time.`,
    tips: ["Defense is almost always more cost-effective than offense. A wall discourages most attackers.", "War consumes food faster. Stock 500+ food before any conflict.", "Ally with at least one strong military nation early. Their Defense Level deters attacks on you."]
  },
  "#budget": {
    title: "Budget Panel Guide",
    screenshot: { label: "Budget Cycle Panel", desc: "Opened via 'Manage'. Shows four tax sliders plus two spending sliders. A live revenue estimator updates as you drag.", visual: ["[Income / Sales / Corporate / Tariff Tax Sliders]", "[Military % / Education % Spending Sliders]", "💰 Est. per-tick revenue: +32 Credits", "📊 Surplus/Deficit: ✅ SURPLUS +14"] },
    content: `**The Budget Cycle**\n\nChanges take effect on the next economic tick (~60s).\n\n**Spending Sliders:**\n- Military Spending % → portion of budget to defense (boosts Unit Power + Defense)\n- Education Spending % → multiplier on Researcher TP output\n\n**Optimal Split (general):**\n- Early game: 20% Military / 25% Education\n- Mid game: 25% Military / 30% Education\n- War time: 40% Military / 20% Education\n\n**Military Spending Effects:**\n| Rate | Effect |\n|---|---|\n| 0–15% | Military stats slowly decay |\n| 15–25% | Stable, no bonus |\n| 25–40% | +Unit Power / Defense bonus |\n| >50% | Max military, significant GDP drag |\n\n**Education Spending → TP Multiplier:**\n| Rate | Multiplier |\n|---|---|\n| 20–30% | ×1.0 (baseline) |\n| 30–35% | ×1.25 |\n| 35–40% | ×1.40 |\n| >40% | ×1.50 (diminishing returns) |`,
    tips: ["Education spending above 35% has diminishing returns. Spend the credits on buildings instead.", "Military spending above 45% causes civilian morale to start declining.", "The budget panel shows your complete financial picture at a glance — check it daily."]
  },
  "#inflation": {
    title: "Inflation Mechanics",
    screenshot: { label: "Inflation Rate Indicator", desc: "Inflation rate in the Metrics panel: green below 5%, amber 5–10%, red above 10%.", visual: ["📈 Inflation: 3.2%  ✅ Healthy", "📈 Inflation: 8.7%  ⚠️ Moderate", "📈 Inflation: 14.1% 🔴 HIGH!", "💸 Resource Prices: +14%  |  Build Costs: +14%"] },
    content: `**How Inflation Works**\n\nInflation rises when money supply grows faster than goods production.\n\nHigh inflation consequences:\n- Resource prices increase (resource_price_mod multiplier)\n- Construction costs increase (construction_cost_mod multiplier)\n- Currency stability falls below 1.0\n- At 25%: severe disruption, stock crashes likely\n\n**Reducing Inflation:**\n1. Raise taxes (removes credits from circulation)\n2. Cut military/education spending\n3. Avoid taking too many loans simultaneously\n4. Improve manufacturing output\n5. Embargo high-inflation trading partners\n\n**Deflation (< -3%):**\nReduces GDP growth. Can cause recession events. Over-taxing causes this.\n\n**Target Zone:** 2–6% inflation is healthy growth.`,
    tips: ["Target 2–6% inflation.", "Wars spike inflation fast. Increased military spending floods the economy with currency.", "Taking multiple loans simultaneously is the fastest way to trigger high inflation."]
  },
  "#wealth": {
    title: "National Wealth Formula",
    screenshot: { label: "National Wealth Breakdown", desc: "National Wealth in Nation Stats below GDP. A composite of all your economic assets.", visual: ["🏦 National Wealth: 18,450", "= 💰 GDP (2,841)", "+ 🏗️ Infrastructure (8,200)", "+ 📦 Resources Value (2,600)", "+ 📈 Corp Market Cap (4,809)"] },
    content: `**National Wealth Components**\n\nNational Wealth = GDP + Infrastructure Value + Resource Stockpile Value + Corporation Market Cap\n\n**Infrastructure Value:**\nTotal market value of all your buildings (~80% of construction cost). Destroyed buildings reduce this.\n\n**Resource Stockpile Value:**\nCurrent stockpiles × global commodity prices. Rises when commodity prices spike.\n\n**Corporation Market Cap:**\nSum of all stock market caps for companies listed in your nation.\n\n**Why National Wealth Matters:**\n- Determines bank loan eligibility\n- Used in global leaderboard rankings\n- Signals economic strength to other players\n- Affects Sovereign Bond package sizes`,
    tips: ["Building investment is the most reliable wealth builder — buildings hold value better than cash.", "Resource stockpiles can be volatile. Don't count on them for long-term wealth planning.", "Multiple listed companies is the fastest path to top-10 national wealth."]
  },
  "#banking": {
    title: "Banking System Guide",
    screenshot: { label: "Banking Panel", desc: "Three loan products: Short-Term, Development, and Sovereign Bond. Each shows interest rate, max principal, and repayment schedule.", visual: ["🏦 Short-Term: 8% | Max 500 | 10 ticks", "🏦 Development: 5% | Max 2,000 | 30 ticks", "🏦 Sovereign Bond: Variable | Players can buy in"] },
    content: `**Loan Types**\n\n**Short-Term Loan:**\n- Small (up to 500), high interest (8%), fast repayment (10 ticks)\n- Use for: emergency liquidity, bridging a resource gap\n\n**Development Loan:**\n- Medium (up to 2,000), lower interest (5%), 30-tick repayment\n- Use for: funding a major building project or epoch advance\n\n**Sovereign Bond:**\n- Large amount, market-rate interest\n- Other players can invest as creditors\n- Use for: major infrastructure expansion, war funding\n\n**Loan Repayment:**\nAuto-deducts repayment_per_tick from treasury each tick. If treasury can't cover, loan defaults.\n\n**Default Consequences:**\n- Stability -20 immediately\n- Credit rating destroyed (higher future interest)\n- Creditor nation notified and paid nothing`,
    tips: ["Never take a loan when already at a treasury deficit.", "Development Loans for Universities almost always pay back many times over.", "Sovereign Bonds are powerful diplomatic tools — debt holders have a financial stake in your stability."]
  },
  "#trade": {
    title: "Trade System Guide",
    screenshot: { label: "Trade Balance Indicator", desc: "Trade Balance in the Metrics panel as a signed number. Positive (green) = surplus. Negative (red) = deficit.", visual: ["⚖️ Trade Balance: +47 Credits/tick  ✅", "Exports: +68  (Wood ×3, Iron ×1)", "Imports: -21  (Gold ×1, Oil ×1)"] },
    content: `**Trade Balance Impact**\n\nTrade Balance directly affects treasury income per tick:\n- Surplus (+) adds credits to treasury\n- Deficit (−) drains credits from treasury\n\n**Building Trade Routes:**\n1. Marketplace → Trade Routes tab\n2. Choose partner nation, resource, quantity, and price\n3. Set direction: Export (you send, they pay) or Import (they send, you pay)\n4. Route activates immediately for AI nations; player nations must accept\n\n**Route Statuses:**\n- Active: Transferring every tick normally\n- Paused: Manually suspended\n- Broken: War between nations or partner bankrupt\n\n**Trade Agreements Reduce Tariffs:**\n- Free Trade: 0% tariff between partners\n- Tariff Reduction: −50% tariff\n- Embargo: blocks all trade`,
    tips: ["Set up export routes for surplus resources before they hit the storage cap.", "Import food if you can't produce enough — cheaper than watching citizens starve.", "Trade routes with allied nations get automatic tariff discounts."]
  },
  "#government-types": {
    title: "Government Type Reference",
    screenshot: { label: "Government Selection", desc: "Government type is chosen during nation creation. A dropdown shows all 15 types with economic profile descriptions.", visual: ["🏛️ Democracy — Balanced | Trust: High", "⚙️ Communist State — High Income | Low Corporate", "⚔️ Military Junta — Max Defense | Low Trust", "🔬 Technocracy — High Education | Tech Bonus"] },
    content: `**All 15 Government Types**\n\n| Type | Income | Corporate | Military% | Education% |\n|---|---|---|---|---|\n| Democracy | 15% | 12% | 20% | 20% |\n| Constitutional Monarchy | 18% | 10% | 22% | 22% |\n| Absolute Monarchy | 20% | 8% | 30% | 15% |\n| Federal Republic | 14% | 14% | 18% | 25% |\n| Socialist Republic | 22% | 6% | 20% | 28% |\n| Communist State | 28% | 5% | 25% | 25% |\n| Oligarchy | 8% | 5% | 25% | 15% |\n| Theocracy | 20% | 10% | 20% | 20% |\n| Military Junta | 15% | 12% | 40% | 15% |\n| Technocracy | 16% | 14% | 15% | 35% |\n| Anarcho-Capitalism | 5% | 3% | 10% | 10% |\n| Direct Democracy | 13% | 13% | 20% | 25% |\n| Feudal Kingdom | 18% | 8% | 28% | 12% |\n| Corporate State | 10% | 18% | 20% | 20% |\n| Confederation | 12% | 10% | 15% | 20% |`,
    tips: ["Technocracy is best for advancing epochs quickly — the education bonus is massive.", "Military Junta is ideal for aggressive early expansion — but manage trust carefully.", "Anarcho-Capitalism is extremely high risk. Only for experienced players."]
  },
  "#buildings": {
    title: "Building Catalogue",
    screenshot: { label: "Construction Hub Grid", desc: "Buildings organized by category tabs: Civilian, Military, Government. Each card shows name, epoch, cost, and primary benefit.", visual: ["[Civilian] [Military] [Government]", "🏠 Housing | 🌾 Farm | 🏭 Factory", "Cost: 50 Wood 30 Stone", "Benefit: +10 Housing Capacity"] },
    content: `**Key Buildings**\n\n**Civilian:**\n- Farm: +food production\n- Granary: +food storage + small production bonus\n- Lumberyard: +20% wood\n- Quarry: +20% stone\n- Gold Mine: +20% gold\n- Iron Mine: +iron (Iron Age+)\n- Oil Rig: +oil (Industrial Age+)\n- Housing: +10 population capacity\n- Warehouse (S/I/Strategic): +5K/+25K/+100K resource storage\n- School / College / University: +TP generation + storage\n\n**Military:**\n- Barracks: +Unit Power, more soldier slots\n- Wall: +Defense Level passive\n- Fortress: Large +Defense (Medieval+)\n- Castle: +Defense +stability\n\n**Government:**\n- Town Hall: +stability, +public trust\n- Central Bank: +currency stability, enables banking\n- National Library: +TP generation, advanced research\n- Palace: +stability, +diplomacy options\n\n**Build Order Advice:**\nFarm → Granary → School → Housing → Quarry → Lumberyard → University`,
    tips: ["Universities are the single best mid-game investment. Don't skip them.", "Walls are cheap and give permanent Defense Level — always have at least one.", "Central Bank unlocks the full banking system. Build it as soon as you have the resources."]
  },
  "#build-order": {
    title: "Early Game Build Order",
    screenshot: { label: "Recommended Build Queue", desc: "Keep the construction queue busy. Early game the queue should rarely sit empty.", visual: ["✅ Farm Lvl 1  (built)", "✅ Granary Lvl 1  (built)", "🔨 School  (building...)", "⏳ Housing Unit  (queued)", "⏳ Quarry  (queued)"] },
    content: `**Recommended Build Order**\n\n**Phase 1 — Survival (Stone Age, first 20 ticks):**\n1. Farm — Secure food supply\n2. Granary — Double food reserves\n3. Housing Unit — Make room for population\n4. School — Start generating Tech Points\n\n**Phase 2 — Foundation (Stone-Bronze, ticks 20–60):**\n5. Quarry — Stone production\n6. Lumberyard — Wood production\n7. Second Housing Unit — Stay ahead of population\n8. Wall — Basic defense\n\n**Phase 3 — Growth (Bronze Age, ticks 60–120):**\n9. Gold Mine — Economic revenue\n10. Barracks — Military capability\n11. Town Hall — Stability boost\n12. College / second School — Accelerate TP\n\n**Phase 4 — Economy (Iron Age+):**\n13. Iron Mine\n14. University — Major TP breakthrough\n15. Central Bank — Unlock banking\n16. Factory (Industrial Age) — GDP multiplier`,
    tips: ["Never let your construction queue sit empty. If unsure, build another Housing Unit.", "Don't build Barracks until Bronze Age — early military spending is wasteful without military techs.", "The School → University path is the most important investment sequence in the game."]
  },
  "#military-buildings": {
    title: "Military Infrastructure Guide",
    screenshot: { label: "Military Buildings Panel", desc: "Military tab in Construction Hub. Each shows Defense Level bonus, Unit Power bonus, and epoch requirement.", visual: ["🧱 Wall — +5 Defense  |  Stone Age  |  40 Stone", "🏰 Fortress — +15 Defense  |  Medieval Age+", "⚔️ Barracks — +8 Unit Power  |  60 Wood 40 Stone", "🗡️ Arsenal — +12 Unit Power  |  Industrial Age+"] },
    content: `**Military Building Overview**\n\n**Defensive Buildings:**\n- Wall (Stone Age): +5 Defense Level. Cheap and essential.\n- Watchtower (Bronze Age): +3 Defense + early warning\n- Fortress (Medieval Age): +15 Defense Level\n- Castle (Medieval Age): +20 Defense + +5 Stability\n- Anti-Air (Modern Age): Specialist high-tier defense\n\n**Offensive Buildings:**\n- Barracks (Stone Age): +8 Unit Power + soldier capacity\n- Military Academy (Classical Age): +15 Unit Power\n- Arsenal (Industrial Age): +12 Unit Power + military tech bonuses\n- War Factory (Industrial Age): Enables heavy unit production\n\n**Strategic Value:**\nEvery 10 Defense Level points reduces incoming attack damage by roughly 15%. A single Fortress can halve early-game attacker effectiveness.\n\n**Garrison Mechanics:**\nBuildings can absorb attack damage. When a building is destroyed, it absorbs damage that would otherwise hit population or resources.`,
    tips: ["Walls first, always. Cheapest and most impactful early defense improvement.", "A Military Academy is worth building in peacetime — Unit Power bonus deters attackers.", "Don't over-invest in offense unless actively at war."]
  },
  "#tech-tree": {
    title: "Full Tech Tree Overview",
    screenshot: { label: "Tech Tree Panel", desc: "Technologies organized in rows by layer, grouped into 5 branches. Unlocked techs glow cyan.", visual: ["[Agriculture] Seed Select → Crop Rotation → Irrigation → GMO Crops", "[Military] Bronze Weapons → Iron → Gunpowder → Rifles → Missiles", "[Industry] Smelting → Forging → Steam Engine → Electricity → Computing"] },
    content: `**Tech Tree Structure**\n\n**Agriculture Branch:**\n- Layer 1: Seed Selection (+10% food), Crop Rotation (+15%)\n- Layer 2: Irrigation (+20%), Animal Husbandry\n- Layer 3: Fertilizers (+30%), Aquaculture\n- Layer 4: Industrial Farming (+50%, Industrial Age)\n\n**Military Branch:**\n- Layer 1: Bronze Weapons (+5 Unit Power)\n- Layer 2: Iron Weapons (+10), Siege Craft\n- Layer 3: Gunpowder (+15, Renaissance)\n- Layer 4: Mechanized Warfare (+20, Industrial)\n\n**Industry Branch:**\n- Layer 1: Smelting (unlock Iron), Basic Forging\n- Layer 2: Steam Engine (+25% manufacturing, Industrial)\n- Layer 3: Electricity (+30% all production, Modern)\n- Layer 4: Computing (+50% TP, Digital)\n\n**Governance Branch:**\nWriting → Currency → Banking → Corporate Law\n\n**Tech Synergies:**\nIron Working + Advanced Metallurgy = +30% iron combined.\nSteam Power + Industrialization = +50% manufacturing combined.`,
    tips: ["Agriculture Layer 1 should be your very first tech purchase. Food bonus pays for itself in 3 ticks.", "Computing (Digital Age) is the most powerful single technology in the game.", "Governance branch unlocks the full diplomatic and economic toolbox."]
  },
  "#research-queue": {
    title: "Research Queue Strategy",
    screenshot: { label: "Research Queue", desc: "Top item actively receiving TP. Below: future queued projects. A progress ring shows 0–100%.", visual: ["🔬 Active: Advanced Metallurgy  [72%]", "⏳ Queued: Nuclear Theory", "⏳ Queued: Space Propulsion", "TP/tick: +14  |  Est. complete: 2 ticks"] },
    content: `**Queue Strategy**\n\nAlways have 2–3 projects queued. Empty queue when project finishes = wasted TP.\n\n**Priority Projects by Epoch:**\n\nStone/Bronze Age:\n- Crop Rotation (fast food boost)\n- Bronze Smelting (Bronze buildings)\n\nIron/Classical Age:\n- Iron Working (Iron Miners)\n- Currency Reform (+15% tax efficiency)\n\nMedieval/Renaissance Age:\n- Banking System (Central Bank + loans)\n- Printing Press (propaganda bonus)\n- Gunpowder (major military boost)\n\nIndustrial Age:\n- Steam Power (biggest GDP multiplier yet)\n- Germ Theory (city health bonus)\n- Railroad Network (trade route bonus)\n\nModern/Digital Age:\n- Nuclear Theory (deterrence + energy)\n- Internet Protocol (TP boost)\n- Satellite Defense (best defensive tech)\n\n**Global Breakthrough Projects (⭐):**\nFirst discoverer gains permanent bonus AND causes rivals to pay extra cost for same research.`,
    tips: ["Banking System is the most economically impactful early research.", "Don't queue military research unless preparing for war.", "Watch the Global Chronicles for breakthrough announcements — rivals' GDP will surge afterward."]
  },
  "#epoch-chart": {
    title: "Epoch Requirements Chart",
    screenshot: { label: "Epoch Advance Button", desc: "When requirements are met, a glowing gold 'Advance to [Next Epoch]' button appears in Nation Stats.", visual: ["🪨 Stone Age → 🥉 Bronze Age", "Requirements: 500 TP + Smelting + Housing T1", "✅ All requirements met!", "[ Advance to Bronze Age → ]  (glowing gold)"] },
    content: `**Epoch Advance Requirements**\n\n| From | To | Min TP | Key Techs |\n|---|---|---|---|\n| Stone | Bronze | 500 | Smelting, Housing T1 |\n| Bronze | Iron | 1,200 | Iron Working, Trade Routes |\n| Iron | Classical | 2,500 | Currency, Writing |\n| Classical | Medieval | 5,000 | Architecture, Feudal Law |\n| Medieval | Renaissance | 9,000 | Banking, Printing Press |\n| Renaissance | Industrial | 16,000 | Steam Power, Factory System |\n| Industrial | Modern | 28,000 | Electricity, Democracy/Republic |\n| Modern | Digital | 45,000 | Computing, Internet Protocol |\n| Digital | Information | 75,000 | AI Research, Cyber Infra |\n| Information | Space | 120,000 | Rocket Science, Orbital Mechanics |\n| Space | Galactic | 200,000 | FTL Theory, Galactic Diplomacy |\n\n**Post-Advance Effects:**\n- All building costs increase ~15%\n- New buildings unlock immediately\n- Global announcement fires`,
    tips: ["Bank TP first, then spend on tech unlocks. You need TP remaining after unlocks to advance.", "The Industrial → Modern transition is the most transformative. The economy fundamentally changes.", "Don't advance if you have less than 300 Credits treasury. Build costs spike immediately."]
  },
  "#map": {
    title: "Map Navigation Guide",
    screenshot: { label: "World Map Interface", desc: "World Map shows all nation territories as colored hex clusters. Your territory glows with your flag color.", visual: ["🔵 Nation A  (blue cluster)", "🔴 Nation B  (red cluster)", "🩵 Your Nation  (cyan cluster)", "⬛ Unclaimed  (dark grey)", "[Zoom +/-  |  Home  |  Overlay toggles]"] },
    content: `**Map Controls**\n\n- Scroll wheel: Zoom in/out\n- Click + drag: Pan the map\n- Click nation icon: Open Nation Interaction menu\n- Click hex tile: View tile details\n- Top-right buttons: Zoom controls, overlay toggles\n\n**Overlays:**\n- Territory View: National ownership by color\n- Resource View: Resource deposits on each hex\n- Military View: Military base locations\n- Infrastructure View: Roads, ports, and buildings\n\n**Nation Icons:**\nEach nation shows a floating icon above their capital hex with flag emoji and GDP/military indicator. Icons pulse red when at war.\n\n**Finding Your Nation:**\nClick the "Home" button in map controls to center on your capital.`,
    tips: ["Resource overlay is invaluable when planning expansion — look for oil and iron deposits.", "Military overlay shows where other nations have built military bases.", "Coastal hexes have a light blue tint. Good for spotting trade port opportunities."]
  },
  "#terrain": {
    title: "Terrain Type Guide",
    screenshot: { label: "Hex Tile Detail", desc: "Clicking a hex tile opens an info panel: terrain type, resource deposit, owner, infrastructure level, and buildings.", visual: ["🟩 Plains — Food +10%, General purpose", "⛰️ Mountains — Stone +20%, Defensible", "🌲 Forest — Wood +25%, Hard terrain", "🌊 Coastal — Trade +15%, Fish bonus", "🏜️ Desert — Oil deposit chance", "❄️ Tundra — Rare minerals"] },
    content: `**Terrain Bonuses**\n\n| Terrain | Primary Bonus | Resource | Strategic Value |\n|---|---|---|---|\n| Plains | +10% food | Food | Farming heartland |\n| Mountains | +20% stone | Stone, Iron | Defensive stronghold |\n| Forest | +25% wood | Wood, Food | Lumber economy |\n| Coastal | +15% trade | Fish, Food | Commerce hub |\n| Desert | — base | Oil (high chance) | Oil extraction zone |\n| Tundra | — base | Rare Minerals | Late-game resource |\n| Ocean | Impassable | — | Naval routes only |\n\n**Strategic Terrain:**\n- Mountains: Attacking across mountains costs +50% military power\n- Forest: Defenders get +15% Defense Level\n- Coastal: Required for Trade Ports (sea trade routes)`,
    tips: ["Try to own at least one desert hex before Industrial Age — oil deposits are extremely valuable.", "Mountains make excellent border tiles. Place military bases on them for maximum defense.", "Coastal hexes are the key to a trade empire. Prioritize claiming them early."]
  },
  "#expansion": {
    title: "Territory Expansion Rules",
    screenshot: { label: "Territory Claiming", desc: "Unclaimed hexes adjacent to your territory show a glowing border on hover. A 'Claim Tile' button appears with resource cost.", visual: ["[Your territory — cyan]", "[Adjacent unclaimed — glowing 🟡]", "[ Claim Tile: 50 Wood + 30 Stone + 20 Gold ]", "Or: Military conquest costs soldiers + attacks"] },
    content: `**Expansion Methods**\n\n**Peaceful (unclaimed tiles):**\n- Click any unclaimed hex adjacent to your territory\n- Pay the resource cost (scales with distance from capital)\n- Tile instantly joins your territory\n- Base cost: ~50 Wood + 30 Stone + 20 Gold (increases per hex)\n\n**Military Conquest (claimed tiles):**\n- Declare war on the tile's owner\n- Launch attacks targeting their territory\n- After sufficient damage, their tiles become claimable\n\n**Cost Scaling:**\nEach additional hex increases next claim cost by ~5%. After 20 hexes, costs are ~100% higher than base.\n\n**Cluster Bonuses:**\nOwning a complete cluster (7 adjacent hexes) grants +10% production in that area.`,
    tips: ["Quality over quantity — 10 well-chosen hexes beat 20 random ones.", "Always prioritize hexes with oil and iron deposits over generic plains.", "Never expand faster than your military can protect. Over-extended borders invite attacks."]
  },
  "#cities": {
    title: "City Founding Guide",
    screenshot: { label: "City Management Page", desc: "City Management shows all founded cities as cards with population, happiness, budget balance, and a manage button.", visual: ["🏙️ Capital: Veldrix  |  Pop: 4,200", "😊 Happiness: 78%  |  Budget: +340/tick", "Crime: 12%  |  Health: 74%", "[ Manage City ]"] },
    content: `**Founding a City**\n\nRequirements: Own the target hex tile + sufficient resources (varies by epoch) + hex must not already have a city.\n\n**Steps:**\n1. City Management page\n2. Click 'Found New City'\n3. Select hex from your territory\n4. Name your city\n5. Choose specialization\n\n**City Specializations:**\n| Type | Bonus | Tradeoff |\n|---|---|---|\n| Balanced | None | None |\n| Industrial | +Manufacturing, +GDP | +Pollution |\n| Agricultural | +Food production | Lower commercial income |\n| Tourist | +Happiness, +Commerce | Lower industrial output |\n| Tech | +TP generation | Higher upkeep |\n\n**Capital City:**\nFirst city = your capital: +10% national GDP, +5 stability, diplomatic significance.\n\n**When to Found Second City:**\nWait until first city has 2,000+ population and budget in surplus.`,
    tips: ["Found your capital on fertile plains or coastal tile.", "Coastal cities are best for the second city. Trade income compounds over time.", "Keep your capital well-serviced. Low happiness there spreads national unrest."]
  },
  "#diplomacy": {
    title: "Diplomacy System Guide",
    screenshot: { label: "Nation Interaction Modal", desc: "Clicking a nation opens the interaction modal: flag, name, government type, key stats, and action buttons.", visual: ["🏴 Republic of Valdorn", "Gov: Federal Republic  |  GDP: 3,420", "⚔️ Military: 82  |  🛡️ Defense: 74", "[ Offer Alliance ] [ Propose Trade ] [ Declare War ] [ Send Aid ]"] },
    content: `**Diplomatic Actions**\n\n**Offer Alliance (10 IP):**\nMutual defense pact. Both parties must accept. Allied nations share Allies chat channel.\n\n**Propose Trade Agreement (5 IP):**\n- Free Trade: 0% tariffs\n- Tariff Reduction: -50% tariffs\n- Embargo: Blocks all trade (hostile)\n\n**Declare War:**\nImmediate. No prerequisites. Consequences: stability drain both nations, pop loss, resource damage. Auto-expires ~3.5 hours.\n\n**Send Aid:**\nTransfer Credits, Resources, or Tech Points. Costs full value. Builds diplomatic goodwill.\n\n**Sanction (15 IP):**\nEconomic penalties on target. More effective in coalitions.\n\n**Spy (20 IP):**\nReveals rough stability, GDP, and military stats. Useful intel before war.\n\n**Influence Points:**\nBase regen: +5/tick. Build National Library or Palace to increase regen rate.`,
    tips: ["Send small aid packages before asking for a formal alliance. Goodwill matters.", "Spy reports are worth 20 IP before any war declaration.", "Never declare war without first checking if they have powerful allies."]
  },
  "#alliances": {
    title: "Alliance Mechanics",
    screenshot: { label: "Allies Panel", desc: "Current allies listed in Nation Stats panel. Each shows flag, name, and military power indicator.", visual: ["🤝 Allies (2):", "🔵 Principality of Auros  ⚔️ 94  🛡️ 88", "🟢 Empire of Thornwall  ⚔️ 67  🛡️ 71"] },
    content: `**Alliance Benefits**\n\n**Mutual Defense:**\nIf attacked, allies receive automatic notification. They can join your defense — their military power adds to your effective Defense Level.\n\n**Trade Bonuses:**\nTrade routes between allied nations get automatic tariff discounts (up to -50%).\n\n**Allies Chat Channel:**\nDedicated channel for multi-party private communication.\n\n**Shared Intel:**\nAllies can see each other's approximate military stats and stability.\n\n**Alliance Risks:**\n- If your ally declares war, you may be dragged in\n- A bankrupt ally can affect diplomatic confidence in you\n\n**Breaking Alliances:**\nCancel any time from Nation Interaction menu. Diplomatic cost: -20 goodwill. May invite retaliation.`,
    tips: ["3 mid-tier allies are better than 1 superpower ally — diversified protection is more stable.", "Check an alliance candidate's stability before aligning. A collapsing nation drags you down.", "The Allies chat channel is invaluable for coordinating trade and defense strategies secretly."]
  },
  "#war": {
    title: "War System Deep Dive",
    screenshot: { label: "War Status Banner", desc: "When at war, a red pulsing banner appears on the Dashboard and in Nation Stats.", visual: ["🔴 WAR: You are at war with Iron Dominion", "⚠️ Stability: -1/tick  |  Population: -1/tick (15%)", "⏱️ Auto-expires in: ~3.2 hours real time"] },
    content: `**War Mechanics**\n\n**During War (every tick):**\n- Your Stability -1\n- 15% chance Population -1\n- Military spending effectiveness +20% (war footing)\n\n**Attack Actions (War Room in Profile):**\nLaunch Attack spends soldiers and deals damage:\n- Building destruction\n- Resource theft\n- Population loss\n- Stability hit on target\n\n**Attack Formula:**\nDamage = (Unit Power / Defense Level) × Base Damage × Random(0.8–1.2)\n\n**War Duration:**\nAuto-expires after ~3.5 real hours. Peace can be negotiated at any time.\n\n**Peace Negotiations:**\nEither party proposes peace via Nation Interaction menu. Other must accept. Terms can include resource transfers.\n\n**Ally Involvement:**\nIf your ally is attacked, you may declare war on the attacker, adding your military to the defender's side.`,
    tips: ["Don't declare war without 500+ food and 300+ treasury in reserve.", "Launch attacks in the first few ticks of war — early pressure is most effective.", "A well-timed peace offer after dealing significant damage is often more profitable than fighting to the end."]
  },
  "#trade-agreements": {
    title: "Trade Agreement Types",
    screenshot: { label: "Trade Agreements Panel", desc: "Marketplace → Trade Agreements tab shows all active agreements with partner, type, tariff modifier, and cycles remaining.", visual: ["✅ Free Trade — Kalindra  |  Tariff: 0%  |  8 cycles left", "📉 Tariff Reduction — Stonemark  |  −50%  |  5 cycles left", "🚫 Embargo — Iron Dominion  |  All blocked  |  12 cycles left"] },
    content: `**Trade Agreement Details**\n\n**Free Trade Agreement:**\n- Tariff Modifier: -100% (zero tariffs)\n- Both nations benefit simultaneously\n- Best for long-term allied trade partners\n- Duration: 10 cycles (renewable)\n\n**Tariff Reduction:**\n- Tariff Modifier: -50%\n- Stepping stone before full free trade\n\n**Embargo:**\n- Blocks ALL trade between nations\n- Hostile diplomatic signal — can trigger counter-sanctions\n- Used as economic warfare\n\n**Proposing an Agreement:**\n1. Marketplace → Trade Agreements tab\n2. Propose Agreement\n3. Select partner, type, duration\n4. They accept or decline\n5. Takes effect immediately upon acceptance\n\n**Expiry:**\nCycles remaining hit 0 → agreement expires. Trade continues at normal tariff rates unless renewed.`,
    tips: ["Embargo is economic war. Only use it if prepared for a diplomatic fallout.", "Free Trade with your primary partner can be worth 30–50 extra credits/tick.", "Counter-tariffs activate automatically when you impose high tariffs on import-dependent nations."]
  },
  "#ipo": {
    title: "IPO Strategy Guide",
    screenshot: { label: "Issue Stock Panel", desc: "Form for your new company: Company Name, Ticker, Sector, Total Shares, Base Price. A preview shows estimated IPO valuation.", visual: ["Company: Valdorian Energy Corp", "Ticker: VEC  |  Sector: Energy", "Shares: 500  |  Base Price: 12", "Est. Market Cap: 6,000 Credits", "IPO Cost: ~200 Credits treasury"] },
    content: `**IPO Mechanics**\n\n**Sector Modifiers:**\n| Sector | Multiplier |\n|---|---|\n| Technology | ×1.4 |\n| Nano | ×1.5 |\n| Energy | ×1.3 |\n| Finance | ×1.2 |\n| Defense | ×1.1 |\n| Agriculture | ×1.0 |\n| Commodity types | ×0.9–1.1 |\n\n**IPO Pricing Formula:**\nBase Price = (GDP × 0.002) × (Public Trust × 0.8) × Sector Modifier × Stability Modifier\n\n**IPO Cost:**\n~3–5% of estimated IPO market cap from treasury.\n\n**Shares & Pricing:**\n500 shares at 10 Credits = same market cap as 1,000 shares at 5 Credits.\nFewer shares = higher per-share price = more attractive per unit.\n\n**After IPO:**\nStock price moves with your nation's economic health every tick.`,
    tips: ["Time your IPO after a GDP growth phase — higher GDP = higher IPO base price.", "Energy sector in Industrial Age gets premium pricing. Hold your Energy IPO until then if possible.", "List 2–3 companies across different sectors to diversify your stock income streams."]
  },
  "#stocks": {
    title: "Stock Valuation Model",
    screenshot: { label: "Stock Price Chart", desc: "Stock detail page shows a 20-tick price history chart. Below: company sector, nation, shares, and available shares.", visual: ["📈 VEC — Valdorian Energy Corp", "[Chart: 8.2 → 9.1 → 10.4 → 11.8 → 12.0]", "Nation: Valdorn  |  Sector: Energy", "Market Cap: 6,000  |  Available: 320/500"] },
    content: `**How Stock Prices Move**\n\n**Price Rise Factors:**\n- GDP growing tick-over-tick\n- Inflation below 5%\n- Stability above 70%\n- No active war\n- New buildings completed\n- Tech unlocked\n\n**Price Fall Factors:**\n- GDP declining\n- Inflation above 10%\n- Stability below 40%\n- Active war\n- Treasury deficit\n- Market crash event\n\n**Market Crash:**\nSevere distress (stability < 15 OR treasury < -200) triggers crash: all prices drop 50–90% instantly. Announced globally.\n\n**Recovery:**\nAfter a crash, prices recover if the nation stabilizes. Bottom-buyers can make significant returns.\n\n**Investment Signals:**\nLook for: consistent GDP growth, low inflation, stable government, no active wars.`,
    tips: ["Invest in nations with consistently growing GDP — growth rate matters most.", "Technology stocks boom in Digital Age regardless of nation health.", "Never put all your Credits into one nation's stocks. Diversify across 3+ nations."]
  },
  "#ticker": {
    title: "Reading the Stock Ticker",
    screenshot: { label: "Stock Ticker Feed", desc: "Live scrolling list: ticker symbol, current price, price change (+green or −red), trend arrow.", visual: ["VEC  $12.0  ▲ +0.8  (+7.1%)", "AXG  $5.3   ▼ -0.4  (-7.0%)", "STN  $8.1   — +0.0  (0.0%)", "IRF  $22.4  ▲ +1.2  (+5.7%)"] },
    content: `**Reading the Feed**\n\nEach entry:\n- Symbol — unique stock identifier\n- Price — current price in Credits\n- Change — price difference from last tick\n- % Change — percentage movement\n- Arrow — ▲ rising, ▼ falling, — flat\n\n**Bullish Signals:**\n- 3+ consecutive green ticks = strong uptrend\n- Price rising above IPO base price = investor confidence\n\n**Bearish Signals:**\n- 3+ consecutive red ticks = downtrend\n- Price falling below 50% of IPO price = distress warning\n- Sudden sharp drop (-20%+) = crash risk\n\n**Price History:**\nClick any ticker to see a 20-tick price history chart.\n\n**Sorting:**\nClick column headers to sort by Price, Change, or %. Use sector filter to narrow results.`,
    tips: ["A stock dropping 3 ticks in a row but the nation's GDP still growing is often a buying opportunity.", "Watch Energy sector stocks when Industrial Age boom is happening — they spike hard.", "Leave the ticker visible in your right panel to catch crashes early."]
  },
  "#crashes": {
    title: "Market Crash Events",
    screenshot: { label: "Market Crash Notification", desc: "A red breaking news banner appears when a crash occurs. Affected stocks in the ticker show large red percentage drops.", visual: ["🔴 BREAKING: Market Crash in Iron Dominion!", "AXG: $5.3 → $0.8  ▼ -84.9%", "IRF: $22.4 → $4.1  ▼ -81.7%"] },
    content: `**How Market Crashes Happen**\n\nA crash triggers when a nation meets:\n- Treasury < -200 Credits\n- Stability < 15\n- Inflation > 20%\n- 2+ moderate conditions simultaneously\n\n**Crash Severity:**\n- Mild Crash: -30 to -50% price drop\n- Severe Crash: -50 to -75%\n- Total Collapse: -75 to -90%\n\n**Duration:**\nCrash flag persists for several ticks. Stocks may continue falling before finding a floor.\n\n**Recovery:**\nNation recovers if they:\n1. Restore treasury to positive\n2. Raise stability above 25\n3. Reduce inflation below 15%\nRecovery is gradual — 5–15 ticks.\n\n**Protecting Yourself:**\nRed/amber indicators in Metrics Panel are early crash warnings.`,
    tips: ["Never hold more than 20% of your portfolio in any one nation's stocks.", "Crashed stocks are high-risk, high-reward. Only buy if you have intel the nation will recover.", "Keep your own stability above 40 and treasury above 200 at all times."]
  },
  "#chat-channels": {
    title: "Chat Channel Guide",
    screenshot: { label: "World Chat Panel", desc: "Three channel tabs: 🌍 Global, 🤝 Allies, 🔊 System. Activity tab shows the Global Ledger.", visual: ["[ 🌍 Global ] [ 🤝 Allies ] [ 🔊 System ] [ 📊 Activity ]", "🏴 Valdorn: Anyone want to trade Iron for Oil?", "🔵 Auros: @Valdorn I have 200 Oil surplus!", "🔊 SYSTEM: Iron Dominion declared war on Stonemark!"] },
    content: `**The Four Chat Channels**\n\n**🌍 Global:**\nVisible to all nations. Use for: public trade proposals, diplomatic announcements, general chat.\nCaution: Everything here is visible to rivals.\n\n**🤝 Allies:**\nOnly visible to you and your allied nations.\nUse for: coordinating military actions, sharing intel, private trade negotiations.\nRequires: at least one active Alliance.\n\n**🔊 System:**\nRead-only. Official game event announcements:\n- Wars declared, major stock crashes, epoch advances, tech breakthroughs\nCheck this regularly.\n\n**📊 Activity (Global Ledger):**\nStructured event log of all significant in-game actions:\n- Stock trades (nation, ticker, amounts, prices)\n- War attacks, treaties signed, aid sent, tech unlocked`,
    tips: ["Read System channel before any major move — recent events can dramatically change your strategy.", "The Activity feed reveals which nations are buying stock in yours. Valuable economic intelligence.", "Global channel is public. Don't announce military plans here."]
  },
  "#commands": {
    title: "Full Chat Command Reference",
    screenshot: { label: "Chat Commands Dropdown", desc: "Typing '/' in chat input shows a dropdown of commands with descriptions. Nation names autocomplete after '@'.", visual: ["/trade @Valdorn  — Propose trade agreement", "/ally @Auros    — Offer an alliance", "/war @Stonemark — Declare war", "/aid @Kalindra  — Send economic aid", "/sanction @X   — Impose sanctions", "/spy @Valdorn   — Gather intelligence"] },
    content: `**Complete Command List**\n\n| Command | Action | Cost |\n|---|---|---|\n| /trade @Nation | Propose trade agreement | 5 IP |\n| /ally @Nation | Offer alliance | 10 IP |\n| /war @Nation | Declare war | Free (costly consequences) |\n| /peace @Nation | Propose peace | 5 IP |\n| /aid @Nation | Send credits as aid | Full credits sent |\n| /sanction @Nation | Impose economic sanctions | 15 IP |\n| /spy @Nation | Get intelligence report | 20 IP |\n| /lend @Nation | Offer a credit loan | Credits held |\n| /trade route @Nation | Open trade route setup | Free |\n\nNation names with spaces: Use quotes — /ally @"Iron Dominion"\n\n**Influence Points:**\nBase regen: +5/tick. Build National Library or Palace to increase regen rate.`,
    tips: ["Spy reports reveal rough stability, GDP, and military before war. Worth the 20 IP.", "Sending even 50 Credits via /aid builds significant diplomatic goodwill.", "/peace mid-war after landing 2–3 successful attacks is often the smart move."]
  },
  "#private-messages": {
    title: "Private Diplomacy Guide",
    screenshot: { label: "Private Message Panel", desc: "The 🔒 lock icon opens the Private Chat panel as a slide-out. Recent conversations on left, active thread on right.", visual: ["[ 🔒 Private Messages ]", "Recent: Valdorn (unread 2) | Auros", "────────────────────────", "Valdorn: 'Let's make a secret deal...'", "You: 'I'm listening...'"] },
    content: `**Private Messaging System**\n\n**Access:** Click the 🔒 lock icon in the World Chat panel header.\n\n**Features:**\n- Send private messages to any nation leader\n- Message threads persist for the session\n- Unread count badges on the lock icon\n- Full reply threading with history\n\n**Diplomatic Uses:**\n\nSecret Alliances: Coordinate military actions without public announcement.\nBehind-the-Scenes Deals: Negotiate resource rates outside the formal trade system.\nPeace Negotiations: Agree on terms before a formal /peace offer.\nIntelligence Sharing: Share /spy results with allies.\n\n**Not Logged:** Private messages don't appear in the Global Activity feed — perfect for sensitive negotiations.`,
    tips: ["Start every potential alliance with a private message to establish trust before /ally.", "During wars, keep a private thread open with the enemy. Peace deals happen here first.", "Private messages are not visible in the chat feed — ideal for confidential diplomacy."]
  },
  "#global-ledger": {
    title: "Global Ledger Guide",
    screenshot: { label: "Activity Tab", desc: "The Activity tab shows a reverse-chronological event log with category icons, timestamps, and descriptions.", visual: ["📊 VEC bought ×50 by Auros @12.0 = 600  [2 ticks ago]", "⚔️ Valdorn attacked Stonemark — 3 buildings  [4 ticks ago]", "🤝 Free Trade: Kalindra ↔ Auros  [8 ticks ago]", "🔬 BREAKTHROUGH: Steam Power — Thornwall  [12 ticks ago]"] },
    content: `**Reading the Global Ledger**\n\n**Event Categories:**\n\n📊 Economic: Stock purchases/sales, trade routes, marketplace transactions, loan events\n\n⚔️ Military: War declarations, attacks (with damage), peace agreements, alliance formations\n\n🔬 Research: Tech Tree unlocks, research completions, epoch advances\n\n🤝 Diplomatic: Trade agreements, aid transfers, sanctions\n\n**Strategic Intelligence:**\n- Track which nations are buying YOUR stocks\n- Watch for rivals getting Steam Power (GDP surge incoming 2–3 ticks later)\n- See who's fighting whom (opportunity to invest in weakened combatant's rival)\n- Monitor loan defaults (signals economic collapse incoming)\n\n**Best Practices:**\nCheck the Ledger at session start to catch up on what happened while offline.`,
    tips: ["A nation just advancing epoch will have rising stocks 2–3 ticks later. Buy before the spike.", "If you see repeated attacks on a nation in the Ledger, their stability is crashing.", "The Activity feed is your free intelligence report on every player."]
  },
  "#city-founding": {
    title: "City Founding Guide",
    screenshot: { label: "Found New City Form", desc: "Form shows: hex tile selector, city name field, specialization dropdown, and resource cost preview.", visual: ["Select Tile: [Your Territory Grid]", "City Name: Veldrix Capital", "Specialization: [ Balanced ▼ ]", "Cost: 100 Wood + 80 Stone + 50 Gold", "[ Found City → ]"] },
    content: `**Everything About Founding Cities**\n\n**Why Found Cities?**\nCities are long-term GDP multipliers. Each city:\n- Adds a population center that grows independently\n- Contributes monthly_income to your national treasury\n- Boosts national GDP via commercial and industrial activity\n\n**Best Tile Choices:**\n| Tile | Best For |\n|---|---|\n| Plains | Agricultural city (food) |\n| Coastal | Commercial city (trade) |\n| Forest | Industrial city (wood) |\n| Mountains | Fortress city (defense) |\n\n**City Cost Scaling:**\n- First: ~100 Wood + 80 Stone + 50 Gold\n- Each subsequent: +25% more than previous\n\n**Capital City:**\nFirst city = your capital: +10% national GDP, +5 stability, diplomatic significance.\n\n**When to Found Second City:**\nWait until first city has 2,000+ population and budget in surplus.`,
    tips: ["Name your cities meaningfully — they appear in the Global Chronicles when events happen.", "Coastal cities are best for the second city. Trade income compounds over time.", "Keep your capital well-serviced. Low happiness there spreads national unrest."]
  },
  "#zoning": {
    title: "Zoning Strategy Guide",
    screenshot: { label: "City Zoning Panel", desc: "Three sliders: Residential %, Commercial %, Industrial % (must sum to 100%). Preview shows Population Cap, Tax Revenue, and Pollution.", visual: ["Residential: [████████░░] 40%  → Pop Cap: 8,000", "Commercial:  [█████░░░░░] 30%  → Tax: +180/tick", "Industrial:  [████████░░] 30%  → Manuf: +25 | Pollution: +12"] },
    content: `**Zoning Effects**\n\n**Residential Zones:**\n- +200 pop capacity per 10% residential\n- Low commercial = lower income but cleaner air\n\n**Commercial Zones:**\n- ~+6 Credits/tick per 10% commercial\n- Attracts businesses, boosts happiness slightly\n\n**Industrial Zones:**\n- Boosts Manufacturing Index (feeds into GDP)\n- Side effect: +Pollution per 10%\n\n**Optimal Splits:**\n| City Type | Residential | Commercial | Industrial |\n|---|---|---|---|\n| Capital | 50% | 35% | 15% |\n| Industrial | 30% | 25% | 45% |\n| Agricultural | 50% | 30% | 20% |\n| Tech Hub | 40% | 35% | 25% |\n| Balanced | 40% | 30% | 30% |\n\n**Pollution:**\nHigh pollution lowers city happiness and health. Industrial Age brings cleaner factories.`,
    tips: ["Don't go above 40% industrial without a hospital. Pollution and disease spike together.", "Your capital should stay primarily residential — max population for tax revenue.", "Commercial zones scale better late game when trade routes generate more activity."]
  },
  "#services": {
    title: "City Services Guide",
    screenshot: { label: "City Services Panel", desc: "Services tab shows four service types with current count, build cost, and effect on city stats.", visual: ["🏫 Schools: 2  |  Education: 68  |  +TP bonus", "🏥 Hospitals: 1  |  Health: 61  |  Disease protection", "👮 Police: 2   |  Crime: 18%  |  Safety +", "🚒 Fire Dept: 1  |  Fire Risk: Low"] },
    content: `**City Services System**\n\n**Schools:**\n- Each: +10 Education Level\n- Education > 60 → bonus Tech Points for your nation\n- Education > 80 → chance of 'Innovation' positive events\n\n**Hospitals:**\n- Each: +10 Health Level\n- Health > 70 → reduced disease outbreak chance\n- Health < 40 → disease outbreaks become common (pop loss, -stability)\n\n**Police Stations:**\n- Each: reduces Crime Rate by 8–12%\n- Crime < 20%: Happiness +5\n- Crime > 40%: -Happiness, protest events\n- Crime > 60%: Potential riot events\n\n**Fire Departments:**\n- Reduces fire disaster frequency by 60% per station\n- Without them, fires can permanently destroy 1–3 buildings\n\n**Service Score (0–100):**\nOverall coverage rating. Score < 40 triggers negative events. Score > 80 triggers positive milestone events.`,
    tips: ["Always build at least 1 Fire Department per city. Fire disasters permanently destroy buildings.", "Police → Hospitals → Schools in priority order for a new city.", "A city with Education Level > 80 is a passive tech point machine in late game."]
  },
  "#city-events": {
    title: "City Events Reference",
    screenshot: { label: "City Events Panel", desc: "Events tab shows pending events as colored cards. Red = critical, yellow = warning, green = positive.", visual: ["🔴 CRITICAL: Disease Outbreak — Health -15, Pop -200  [ Respond ]", "🟡 WARNING: Workers Strike — Manufacturing -20%  [ Negotiate / Suppress ]", "🟢 POSITIVE: Immigration Wave — Pop +500  [ Accommodate ]"] },
    content: `**City Event Types**\n\n**Crime Events:**\nTriggered by Crime Rate > 40%. Response: increase police funding or crack down (martial law risk).\n\n**Disease Outbreaks:**\nTriggered by Health Level < 40%. Response: emergency healthcare funding.\nCritical outbreak: -500 to -2,000 population, -10 national stability.\n\n**Fires:**\nTriggered without Fire Departments. After the fact: building loss is permanent.\n\n**Protests:**\nTriggered by happiness < 40% or high taxes.\n\n**Immigration Waves:**\nTriggered by happiness > 75% + good health + low crime. Pure positive! Population surge 200–1,000.\n\n**Achievements:**\nTriggered by milestones. Generate positive news in Global Chronicles.\n\n**Unresolved Events:**\nNot responded to within 5 ticks → worst outcome defaults automatically.`,
    tips: ["Check City Events every session. One ignored critical event can spiral into national instability.", "Immigration waves are pure positives — make sure housing capacity can absorb them.", "Disease outbreaks in early game (no hospital) are the most dangerous city events."]
  },
  "#commodities": {
    title: "Commodity Market Guide",
    screenshot: { label: "Global Commodity Market Table", desc: "Marketplace shows all tradeable commodities with current price, history sparkline, global supply, global demand, and buy/sell buttons.", visual: ["Food   $8.2/100u  📈  Supply: 48K  Demand: 52K  [Buy][Sell]", "Wood   $5.1/100u  📉  Supply: 65K  Demand: 41K  [Buy][Sell]", "Iron   $14.8/100u ↗  Supply: 12K  Demand: 18K  [Buy][Sell]", "Oil    $22.1/100u 🚀  Supply: 8K   Demand: 19K  [Buy][Sell]"] },
    content: `**Global Commodity Market**\n\n**Price Mechanics:**\n- High demand + low supply = rising price\n- High supply + low demand = falling price\n- Shortage events spike prices dramatically (50–200%)\n\n**When to Buy:**\n- Price below historical average\n- Before known demand spikes (Iron before Industrial boom)\n- When a major producer nation goes to war (supply disruption)\n\n**When to Sell:**\n- Price > 150% of base price (take profits)\n- Excess resources approaching storage cap\n\n**Base Prices (approximate):**\nFood: $10/100u | Wood: $6/100u | Stone: $5/100u | Iron: $15/100u | Oil: $25/100u\n\n**Shortage Events:**\nWhen global_supply < global_demand × 0.8, shortage activates. Prices spike until supply catches up.`,
    tips: ["Oil is chronically in shortage in mid-to-late game. Stockpile early and sell at peak.", "Food prices crash when many nations reach Granary Tier 3. Avoid over-investing in food production then.", "Iron demand spikes globally at Iron Age transitions. Stockpile iron just before reaching Iron Age."]
  },
  "#trade-routes": {
    title: "Trade Route Setup Guide",
    screenshot: { label: "Trade Route Card", desc: "Active routes appear as cards: partner flag, resource icon, quantity, price, direction arrow, status badge, and lifetime statistics.", visual: ["🚢 Export → Principality of Auros", "🪵 Wood  ×50/tick  @$6.0/100u", "Status: ✅ Active  |  Cycles: 23  |  Earned: 1,380 Credits"] },
    content: `**Trade Route System**\n\n**Creating a Route:**\n1. Marketplace → Trade Routes tab\n2. Click 'Create Route'\n3. Select: partner nation, resource, quantity, price per 100 units\n4. Direction: Export (you send, they pay) or Import (they send, you pay)\n5. Auto-activates for AI nations; player nations must accept\n\n**Export Routes:**\nResources out, credits in. Best when resources are near storage cap.\n\n**Import Routes:**\nResources in, credits out. Best when critically low on a resource.\n\n**Route Statuses:**\n- Active: Transferring normally\n- Paused: Manually suspended\n- Broken: War between nations or partner bankrupt\n\n**Tariffs:**\nApplied on all imports based on your tariff rate. Free Trade Agreements remove this.`,
    tips: ["Price exports slightly above market rate with allies — they won't mind, and you earn more.", "Always have backup reserves if an import route breaks. Keep 50+ of any critical import.", "Multiple small routes to different nations is safer than one huge route to a single partner."]
  },
  "#specialization": {
    title: "Trade Specialization Guide",
    screenshot: { label: "Trade Balance Overview", desc: "The Trade Balance indicator shows your net credits per tick from all active routes.", visual: ["⚖️ Trade Balance: +62 Credits/tick", "📤 EXPORT: Wood (3 routes), Stone (1 route)", "📥 IMPORT: Oil (1 route), Iron (2 routes)"] },
    content: `**Specialization Strategy**\n\n**Why Specialize?**\nNations producing everything end up mediocre at everything. Specialization lets you maximize strengths and trade for the rest.\n\n**Identifying Your Strengths:**\n- Forest hexes → Wood specialization\n- Desert hexes → Oil specialization (Industrial Age)\n- Coastal hexes → Fish/Food or Trade specialization\n- Mountain hexes → Stone/Iron specialization\n\n**Classic Trading Pairs:**\n| Nation A | Nation B | Exchange |\n|---|---|---|\n| Wood exporter | Stone exporter | Both benefit |\n| Food producer | Iron miner | Food for Iron |\n| Oil producer | Grain producer | Energy for food |\n\n**When to Diversify:**\n- Early (Stone-Bronze): Produce everything for self-sufficiency\n- Mid (Iron-Industrial): Specialize in 2 exports, import 2–3 others\n- Late (Digital+): Full specialization + financial exports`,
    tips: ["The best trade partnerships are with nations that have opposite terrain bonuses to yours.", "Don't specialize in oil until Industrial Age — production is zero before that.", "Financial exports (stock dividends, loan interest) become your biggest income source in late game."]
  },
  "#policies": {
    title: "Policy Toggle Effects",
    screenshot: { label: "Policy Center", desc: "Policy Center (Government page) shows all toggles as flip switches. Active policies glow green.", visual: ["💊 Healthcare  [ON ✅]  +Stability +Health  |  Cost: 15 Credits/tick", "⚔️ Martial Law  [OFF ❌]  +Defense -Trust  |  Cost: 10 Credits/tick", "🔬 Tech Subsidies [ON ✅]  +TP Gen  |  Cost: 20 Credits/tick"] },
    content: `**All Policy Toggles**\n\n**Healthcare (15 Credits/tick):**\n+5 stability/tick, +city health scores.\nBest when stability < 60 and treasury is healthy.\n\n**Martial Law (10 Credits/tick):**\n+10 Defense Level, -8 Public Trust.\nWarning: Prolonged use (10+ ticks) triggers protest events.\n\n**Tech Subsidies (20 Credits/tick):**\n+25% Tech Point generation rate.\nBest when racing to advance an epoch. Turn off after epoch advance.\n\n**Tax Cuts:**\n+0.15 Public Trust/tick, +5% GDP growth.\nCost: -15% tax revenue.\nDon't use during treasury deficit.\n\n**Conscription:**\n+15 soldiers immediately, +8 Unit Power.\nCost: -0.10 Trust, -2 Stability.\nWarning: Long-term use tanks trust severely.\n\n**Propaganda (1× per day, 20 IP):**\nPublishes government article in Global Chronicles.`,
    tips: ["Never run more than 2 expensive policies simultaneously — treasury drain adds up fast.", "Tech Subsidies + full Researchers = fastest way to advance epochs.", "Turn off Martial Law immediately when the immediate threat passes. Trust is very slow to recover."]
  },
  "#dilemmas": {
    title: "Council Dilemma Guide",
    screenshot: { label: "Council Dilemma Modal", desc: "A centered overlay with dramatic header, the dilemma description, and two large option buttons.", visual: ["⚖️ COUNCIL DILEMMA", "A drought has struck your farmlands.", "Option A: 'Emergency Rations' → -100 Credits, +Stability +5", "Option B: 'Ration Population' → -Public Trust, no treasury cost"] },
    content: `**Council Dilemma System**\n\n**What Are Dilemmas?**\nRandom binary decisions with real consequences. Simulate difficult governing choices.\n\n**How Often:**\nRoughly every 10–30 ticks. More frequent with low stability, high population, or active war.\n\n**Dilemma Sources:**\n| Source | Type |\n|---|---|\n| Citizen | Labor disputes, protests, housing demands |\n| Company | Corporate regulation, IPO disputes |\n| Advisor | Military strategy, economic policy, diplomatic crises |\n| Ally | Alliance obligations, joint military decisions |\n\n**Response Timer:**\n~10 ticks to respond. Unanswered = worst option defaults automatically.\n\n**Effect Preview:**\nBrief summary shown. Full secondary effects aren't revealed — part of the challenge.\n\n**Reaction Toast:**\nAfter choosing, a brief citizen reaction message hints at hidden secondary effects.`,
    tips: ["When in doubt, choose the option that protects stability — treasury can be recovered, collapsed stability cannot.", "Never ignore a dilemma. The auto-default is always the worst outcome.", "Certain dilemmas have a government-type-dependent 'correct' answer."]
  },
  "#propaganda": {
    title: "Propaganda Mechanics",
    screenshot: { label: "Propaganda Publisher", desc: "Form with: Article Title, Body, Category, and 'Mark as Official Statement' checkbox.", visual: ["📰 Publish Government Statement", "Title: 'Valdorn Achieves Record GDP Growth'", "Category: Economy  |  ✅ Official Statement", "[ Preview → ] [ Publish (20 IP) ]"] },
    content: `**Propaganda System**\n\n**Purpose:**\n1. Shape world opinion — tell your version of events\n2. Signal intentions — public diplomatic announcements\n3. Deter threats — highlight military strength\n4. Economic signaling — attract investors to your stocks\n\n**Cost:** 20 Influence Points. One article per real-world day.\n\n**Article Types:**\n- Economy: GDP announcements, investment opportunities\n- Military: War declarations, peace offers, strength demonstrations\n- Policy: Legislative announcements, policy changes\n- Tech: Epoch advance celebrations, breakthrough announcements\n- Propaganda (Op-Ed): Opinionated takes, counter-narratives\n\n**Backfire Risk:**\nArticles making false claims (verifiable via the Ledger) can reduce public trust if other players debunk them.`,
    tips: ["Publish propaganda after a major achievement to attract investors to your stocks.", "Counter-propaganda immediately after being attacked — shape the narrative first.", "Propaganda after an epoch advance signals to investors that your stocks are about to rise."]
  },
  "#chronicles": {
    title: "Global Chronicles Reading Guide",
    screenshot: { label: "Global Chronicles Page", desc: "Newspaper-style layout: breaking news ticker at top, articles by tier below. Category filter bar.", visual: ["🔴 BREAKING: War erupts between Valdorn and Stonemark!", "🥇 GOLD: Thornwall enters Industrial Age — GDP +40%", "📰 Standard: Kalindra posts record grain harvest", "[ Filter: All | War | Economy | Tech | Policy ]"] },
    content: `**Article Tiers**\n\n🔴 **Breaking News (auto-generated):**\nCritical world events: war declarations, severe stock crashes, major epoch advances, global shortages.\nAlways read first — immediate strategic implications.\n\n🥇 **Gold Tier:**\nMajor events: GDP milestones, large tech breakthroughs, major alliance formations.\n\n📰 **Standard:**\nRegular activity: minor diplomatic events, trade agreements, city milestones, player propaganda.\n\n**Category Filters:**\n- War: Military events, attacks, peace agreements\n- Economy: GDP changes, market events, trade agreements\n- Tech: Research completions, epoch advances, breakthroughs\n- Policy: Government decisions, dilemma resolutions\n- Propaganda: Player-published articles\n\nArticles older than 30 minutes are filtered out.`,
    tips: ["A Gold-tier epoch advance announcement = buy that nation's stocks immediately.", "Breaking war news = check if your trade partners are involved — routes may break.", "Propaganda claiming great things? Cross-check the Global Ledger to verify."]
  },
  "#core-metrics": {
    title: "Core Metrics Reference",
    screenshot: { label: "Nation Metrics Panel", desc: "Five progress bars: Stability, Public Trust, Manufacturing Index, Defense Level, Unit Power. Color-coded: green/amber/red.", visual: ["⚖️ Stability:       [████████░░] 78  ✅", "🤝 Public Trust:   [███████░░░] 0.7 ✅", "🏭 Manufacturing:  [████░░░░░░] 43  ⚠️ Low", "🛡️ Defense Level:  [█████░░░░░] 52  ⚠️", "⚔️ Unit Power:    [███░░░░░░░] 31  📉"] },
    content: `**Core Metrics Deep Dive**\n\n**Stability (0–100):**\nMost important metric.\n- > 70: Healthy, growth bonuses\n- 40–70: Neutral, normal operation\n- 20–40: Unrest risk, GDP drag\n- < 20: Crisis mode — population fleeing\n- < 10: Political collapse risk\n\nRaises: Healthcare policy, Town Hall, good dilemma choices, peace\nLowers: War (-1/tick), famine events, martial law side effects\n\n**Public Trust (0.1–2.0):**\nMultiplies tax revenue effectiveness.\n- > 1.2: +20% tax revenue bonus\n- < 0.5: Severe unrest, protest events\n\n**Manufacturing Index (0–100):**\nDirect GDP multiplier. Each +10 ≈ +2% GDP growth.\n\n**Defense Level (0–200+):**\nBase 10 + Wall/Fortress bonuses + military techs\n\n**Unit Power (0–200+):**\nBase 10 + Barracks bonuses + soldier count + military techs`,
    tips: ["Stability is the most important stat. A stable poor nation is safer than a wealthy unstable one.", "Manufacturing Index from 30 → 60 adds 15%+ to GDP. Often overlooked.", "Defense Level above 80 makes you essentially immune to early-game attackers."]
  },
  "#fuel": {
    title: "Energy Economy Guide",
    screenshot: { label: "Fuel Price Display", desc: "Fuel Prices section in Metrics panel shows Domestic Fuel Price and Global Oil Price. A war surcharge indicator appears when at war.", visual: ["⛽ Domestic Fuel: 12.4 Credits/unit", "🌍 Global Oil Price: 22.1 Credits/unit", "⚔️ War Surcharge: +30%  (at war)", "💸 Est. Monthly Cost: 180 Credits"] },
    content: `**The Energy Economy**\n\nDomestic Fuel = Global Oil Price × (1 + InflationRate) × WarSurcharge × PopulationDemandFactor\n\n**Why Fuel Costs Matter:**\n- High prices increase construction costs\n- High prices reduce manufacturing efficiency\n- At extreme prices (>30 Credits/unit), factories underperform\n\n**Controlling Fuel Costs:**\n1. Build Oil Rigs (Industrial Age+): domestic supply reduces market dependence\n2. Strategic Oil Reserve: stockpile during cheap periods\n3. Energy Plants: convert oil to energy more efficiently\n4. Nuclear Power (Digital Age): eliminates oil dependence entirely\n\n**Oil Rigs vs Import:**\n- Oil Rigs: upfront build cost, long-term domestic supply\n- Importing: no upfront cost, market price exposure\n- Recommendation: Build 1–2 oil rigs at Industrial Age, supplement with imports\n\n**War Energy Costs:**\nActive war applies +20–30% surcharge. Factor this into war planning.`,
    tips: ["Stockpile 500+ oil units before Industrial Age — demand spikes hard and prices follow.", "Nations controlling oil exports become geopolitically powerful in Industrial Age.", "Nuclear Power in Digital Age eliminates fuel costs almost entirely."]
  },
  "#spending": {
    title: "Spending Optimization Guide",
    screenshot: { label: "Spending Gauges", desc: "Two circular gauges show Military Spending % and Education Spending % as donut charts.", visual: ["⚔️ Military Spending: 25%  [●●●●○]", "🎓 Education Spending: 30%  [●●●●●]", "Remaining: 45% budget"] },
    content: `**Spending Rate Effects**\n\n**Military Spending %:**\n| Rate | Effect |\n|---|---|\n| 0–15% | Military stats slowly decay |\n| 15–25% | Stable, no bonus |\n| 25–40% | +Unit Power +Defense Level |\n| >50% | Max military, significant GDP drag |\n\n**Education Spending % → TP Multiplier:**\n| Rate | Multiplier |\n|---|---|\n| 20–30% | ×1.0 (baseline) |\n| 30–35% | ×1.25 |\n| 35–40% | ×1.40 |\n| >40% | ×1.50 (diminishing returns) |\n\n**Optimal Split by Situation:**\n| Situation | Military | Education |\n|---|---|---|\n| Peacetime growth | 20% | 30% |\n| War preparation | 35% | 20% |\n| Active war | 45% | 15% |\n| Post-war recovery | 15% | 35% |\n| Epoch rush | 20% | 40% |`,
    tips: ["35% Education + full Researchers + Universities = fastest possible epoch advancement.", "Never drop below 15% Military in peacetime — stats quietly decay.", "In late game, financial income from stocks/loans lets you sustain higher spending."]
  },
  "#tech-list": {
    title: "Technology Achievement Guide",
    screenshot: { label: "Unlocked Technologies Grid", desc: "Bottom of Metrics Panel shows a scrollable grid of tech badges. Hover for exact stat effect.", visual: ["✅ Seed Selection (+10% food)", "✅ Bronze Smelting (Bronze buildings)", "✅ Iron Working (Iron Miners)", "✅ Currency Reform (+15% tax efficiency)", "🔒 Steam Power (need Industrial Age)"] },
    content: `**Technology Achievement System**\n\n**How Tech Persists:**\nOnce unlocked, technologies are permanent and never expire. They compound over your nation's lifetime.\n\n**Tech Categories:**\n\n🌾 Agriculture Techs: Food production multipliers. Best early ROI.\n\n⚔️ Military Techs: Unit Power and Defense Level. Cumulative each tier.\n\n🏭 Industry Techs: Manufacturing improvements and reduced construction costs. Biggest GDP impact.\n\n🏛️ Governance Techs: Tax efficiency, diplomacy options, and stability generation.\n\n🚀 Frontier Techs: Space-age bonuses requiring enormous TP investment.\n\n**Tech Synergies:**\n- Iron Working + Advanced Metallurgy = +30% iron combined\n- Currency Reform + Banking System = +25% tax efficiency combined\n- Steam Power + Industrialization = +50% manufacturing combined`,
    tips: ["Agriculture techs have the best early ROI — unlock them before anything else.", "Currency Reform + Banking is worth more Credits per tick than almost any single building.", "The earliest tech investments compound the most — prioritizing production bonuses early pays off enormously."]
  },
};